export const site = {
  name: 'Big Walk Walkthrough',
  url: 'https://bigwalkwalkthrough.com',
  taxonomy: ['tower', 'area', 'item', 'achievement'],
};

export const guides = [
  {
    slug: 'puzzles/green-chair-headphones',
    kind: 'puzzle',
    title: 'Green Chair & Headphones Hint',
    h1: 'Green Chair and Headphones: Hint & Verification Status',
    description:
      'Need help with the green chair and headphones puzzle in Big Walk? Read a spoiler-free hint; a verified solution and original marked screenshots will be added after first-hand verification.',
    verificationStatus: 'pending',
    status: 'draft',
    evidenceLevel: 'not_collected',
    indexable: false,
    category: 'item',
    tower: 'Tower verification pending',
    area: 'Green chair',
    aliases: ['green chair', 'headphones clue'],
    visualCues: ['green chair', 'headphones'],
    nearbyLandmarks: [],
    goal: 'Identify what the visible clue refers to.',
    worldVariants: { twoPlayer: null, threePlayer: null, fourPlus: null },
    prerequisites: [],
    steps: [],
    commonFailures: [],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sources: [],
    hint: 'Inspect nearby visual clues.',
    lastVerified: 'First-hand verification pending',
    updated: '2026-08-08',
    readTime: '2 min read',
    imageAlt: 'green chair and headphones puzzle location in Big Walk',
    assetRequirement: 'green-chair-headphones-location.webp',
    relatedSlugs: ['puzzles/purple-things-where-to-use', 'puzzles/4166-1899-coordinates'],
  },
  {
    slug: 'puzzles/purple-things-where-to-use',
    kind: 'puzzle',
    title: 'Purple Things Hint & Verification Status',
    h1: 'Where Do the Purple Things Go? Hint & Verification Status',
    description:
      'Need help with the purple items in Big Walk? Read a spoiler-free hint; a verified placement guide and original marked screenshots will be added after first-hand verification.',
    verificationStatus: 'pending',
    status: 'draft',
    evidenceLevel: 'not_collected',
    indexable: false,
    category: 'item',
    tower: 'Tower verification pending',
    area: 'Purple items',
    aliases: ['purple things', 'purple items'],
    visualCues: ['purple items'],
    nearbyLandmarks: [],
    goal: 'Identify whether the item has a verified placement or use.',
    worldVariants: { twoPlayer: null, threePlayer: null, fourPlus: null },
    prerequisites: [],
    steps: [],
    commonFailures: [],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sources: [],
    hint: 'Keep the item context in view.',
    lastVerified: 'First-hand verification pending',
    updated: '2026-08-08',
    readTime: '2 min read',
    imageAlt: 'where to place purple things in Big Walk map screenshot',
    assetRequirement: 'purple-things-location-map.webp',
    relatedSlugs: ['puzzles/green-chair-headphones', 'puzzles/4166-1899-coordinates'],
  },
  {
    slug: 'puzzles/4166-1899-coordinates',
    kind: 'puzzle',
    title: '4166 1899 Coordinates Hint & Verification Status',
    h1: '4166 1899 Coordinates: Hint & Verification Status',
    description:
      'See "4166 1899" in Big Walk? Read a spoiler-free hint; the verified interpretation and original marked screenshots will be added after first-hand verification.',
    verificationStatus: 'pending',
    status: 'draft',
    evidenceLevel: 'not_collected',
    indexable: false,
    category: 'area',
    tower: 'Tower verification pending',
    area: 'Coordinates',
    aliases: ['4166 1899', '4166-1899'],
    visualCues: ['4166', '1899', 'coordinates'],
    nearbyLandmarks: [],
    goal: 'Identify what the number pair refers to in the current game version.',
    worldVariants: { twoPlayer: null, threePlayer: null, fourPlus: null },
    prerequisites: [],
    steps: [],
    commonFailures: [],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sources: [],
    hint: 'Keep the number context in view.',
    lastVerified: 'First-hand verification pending',
    updated: '2026-08-08',
    readTime: '2 min read',
    imageAlt: '4166 1899 coordinates clue in Big Walk',
    assetRequirement: '4166-1899-coordinates-clue.webp',
    relatedSlugs: ['puzzles/green-chair-headphones', 'puzzles/purple-things-where-to-use'],
  },
  {
    slug: 'walkthrough/red-tower-map-room',
    kind: 'walkthrough',
    title: 'Red Tower Map Room Hint & Verification Status',
    h1: 'Red Tower Map Room: Hint & Verification Status',
    description:
      'Need help with the Red Tower map room in Big Walk? Read a spoiler-free hint; a verified walkthrough and original marked screenshots will be added after first-hand verification.',
    verificationStatus: 'pending',
    status: 'draft',
    evidenceLevel: 'not_collected',
    indexable: false,
    category: 'tower',
    tower: 'Red Tower',
    area: 'Red Tower',
    aliases: ['red tower map room', 'map room'],
    visualCues: ['red tower', 'map room'],
    nearbyLandmarks: [],
    goal: 'Document the map room route and objective after a first-hand check.',
    worldVariants: { twoPlayer: null, threePlayer: null, fourPlus: null },
    prerequisites: [],
    steps: [],
    commonFailures: [],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sources: [],
    hint: 'Revisit the immediately visible objective area.',
    lastVerified: 'First-hand verification pending',
    updated: '2026-08-08',
    readTime: '2 min read',
    imageAlt: 'red tower map room entrance in Big Walk',
    assetRequirement: 'red-tower-map-room-entrance.webp',
    relatedSlugs: ['home'],
  },
];

export const siteSections = [
  {
    slug: 'beginner-guide', title: 'Big Walk Beginner Guide — Verification in Progress', h1: 'Big Walk Beginner Guide',
    description: 'A first-hand Big Walk beginner guide is being prepared for the current version.', active: 'beginner',
    scope: 'The finished guide will explain the opening loop, how to preserve discovery, and where a verified reference can help without presenting guesses as gameplay facts.',
    evidenceNeeds: ['A complete first-hand opening session.', 'Version-checked notes for every beginner recommendation.', 'Original screenshots where visual orientation matters.'],
    relatedSlugs: ['beginner-guide/can-you-play-solo', 'puzzles'], illustration: 'walker', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'achievements', title: 'Big Walk Achievements and Trophies — Verification in Progress', h1: 'Big Walk Achievements and Trophies',
    description: 'A verified Big Walk achievements reference is being prepared with first-hand requirements and annotated evidence.', active: 'achievements',
    scope: 'Individual achievement pages will only be created after a hard requirement has been verified and the page can offer more than a title or recycled description.',
    evidenceNeeds: ['A first-hand completion record for each achievement.', 'The requirement and platform checked against the current version.', 'Screenshots only where they clarify a condition or location.'],
    relatedSlugs: ['puzzles'], illustration: 'trophy', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer/best-group-size', title: 'Best Big Walk Group Size — Verification in Progress', h1: 'What Is the Best Group Size in Big Walk?',
    description: 'A first-hand comparison of Big Walk group sizes is being prepared.', active: 'multiplayer',
    scope: 'The finished comparison will distinguish directly observed communication and exploration differences by group size, instead of treating community preference as a universal answer.',
    evidenceNeeds: ['Comparable first-hand sessions at more than one group size.', 'The tested version and platform for every session.', 'Notes that separate observed differences from player preference.'],
    relatedSlugs: ['multiplayer', 'beginner-guide/can-you-play-solo'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'puzzles/purple-challenges',
    title: 'Purple Challenges in Big Walk — Verification Tracker',
    h1: 'Purple Challenges: Verification Tracker',
    description: 'A dedicated tracker for purple challenge reports in Big Walk. The total, rewards, and player-count differences will be added only after first-hand verification.',
    active: 'puzzles',
    scope: 'This page will keep the purple challenge cluster in one place: how to recognise a reported challenge, the evidence needed to distinguish it from a visual lookalike, and links to verified individual guides when they exist.',
    evidenceNeeds: ['First-hand captures showing each distinct purple challenge.', 'Version and platform recorded for every observation.', 'Repeatable notes for any player-count or reward difference.'],
    relatedSlugs: ['puzzles/purple-things-where-to-use', 'puzzles/green-chair-headphones'],
    illustration: 'map',
    status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'walkthrough', title: 'Big Walk Walkthroughs — Verification in Progress', h1: 'Big Walk Walkthroughs',
    description: 'A route-based walkthrough hub for Big Walk. Only first-hand, version-checked routes will be added.', active: 'puzzles',
    scope: 'Use this hub to reach verified area walkthroughs. It intentionally does not invent routes, unlock conditions, or rewards before those details are observed.',
    evidenceNeeds: ['A complete first-hand route recording.', 'Landmark screenshots that can be independently matched.', 'A current-version check of all prerequisites and outcomes.'],
    relatedSlugs: ['walkthrough/red-tower-map-room', 'puzzles'], illustration: 'map', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer', title: 'Big Walk Multiplayer & Saves — Verification in Progress', h1: 'Big Walk Multiplayer and Saves',
    description: 'A single hub for first-hand Big Walk multiplayer, hosting, save, and connection notes.', active: 'multiplayer',
    scope: 'This hub separates questions about group play, hosting and saves, finding players, and reconnecting after a disconnect so evidence can be updated without blending different behaviours together.',
    evidenceNeeds: ['A controlled multiplayer session with the tested game version.', 'Host and joiner observations recorded separately.', 'Platform and save-state evidence for each conclusion.'],
    relatedSlugs: ['multiplayer/best-group-size', 'multiplayer/hosting-and-saves', 'multiplayer/transfer-save-to-new-host', 'multiplayer/how-to-find-players'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer/hosting-and-saves', title: 'Big Walk Hosting and Saves — Verification in Progress', h1: 'Big Walk Hosting and Saves',
    description: 'A first-hand reference for hosting, joining, leaving, and save behaviour in Big Walk is being prepared.', active: 'multiplayer',
    scope: 'The finished page will distinguish host behaviour from joiner behaviour and document only save handling that can be reproduced in the current version.',
    evidenceNeeds: ['A host session and a separate joiner session.', 'Observed save state before and after leaving.', 'Original screenshots or recordings of the relevant menus and prompts.'],
    relatedSlugs: ['multiplayer', 'multiplayer/transfer-save-to-new-host', 'troubleshooting/cant-rejoin-after-disconnect'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer/transfer-save-to-new-host', title: 'Transfer a Big Walk Save to a New Host — Verification in Progress', h1: 'Transfer a Big Walk Save to a New Host',
    description: 'This page is reserved for a verified save-transfer workflow, if the current game version supports one.', active: 'multiplayer',
    scope: 'No transfer path is claimed here yet. Once tested, the guide will state the exact supported conditions, platform limits, and recovery advice.',
    evidenceNeeds: ['A repeatable transfer test from the original host to a new host.', 'The exact platform and game version.', 'A before-and-after record that confirms what progress is preserved.'],
    relatedSlugs: ['multiplayer', 'multiplayer/hosting-and-saves'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer/how-to-find-players', title: 'Find Big Walk Players — Verification in Progress', h1: 'How to Find Big Walk Players',
    description: 'A curated, safety-conscious list of active ways to find Big Walk players will be added after sources are checked.', active: 'multiplayer',
    scope: 'The finished page will link to official or clearly identified community spaces and explain what has been checked, instead of implying that a particular group is active.',
    evidenceNeeds: ['An official community or developer-listed contact point.', 'A date-checked community source where activity can be observed.', 'A review of safety and moderation expectations before linking.'],
    relatedSlugs: ['multiplayer', 'multiplayer/best-group-size'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting', title: 'Big Walk Troubleshooting — Verification in Progress', h1: 'Big Walk Troubleshooting',
    description: 'A diagnostic hub for reproducible Big Walk connection, voice, cross-play, and startup problems.', active: 'puzzles',
    scope: 'Each troubleshooting topic will remain separate so reports for one platform or symptom are not mistakenly applied to every player.',
    evidenceNeeds: ['A reproducible issue report with platform and game version.', 'A confirmed resolution or a clearly labelled workaround.', 'A source or first-hand record for every technical recommendation.'],
    relatedSlugs: ['troubleshooting/cant-rejoin-after-disconnect', 'troubleshooting/voice-chat-not-working', 'troubleshooting/crossplay-switch-2', 'troubleshooting/white-screen-and-crash'], illustration: 'map', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting/cant-rejoin-after-disconnect', title: 'Cannot Rejoin Big Walk After a Disconnect — Verification in Progress', h1: 'Cannot Rejoin After a Disconnect',
    description: 'A reproducible diagnosis for Big Walk rejoin failures is being prepared.', active: 'puzzles',
    scope: 'The completed guide will separate a temporary connection interruption from an unsupported session state and will name the tested platform and version.',
    evidenceNeeds: ['Steps that reproduce the rejoin failure.', 'Host and joiner observations.', 'A tested result for each proposed recovery step.'],
    relatedSlugs: ['troubleshooting', 'multiplayer/hosting-and-saves'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting/voice-chat-not-working', title: 'Big Walk Voice Chat Not Working — Verification in Progress', h1: 'Big Walk Voice Chat Not Working',
    description: 'A platform-specific Big Walk voice chat diagnostic is being prepared from reproducible tests.', active: 'puzzles',
    scope: 'The completed guide will list only settings, permissions, and recovery steps that were tested on the named platform and game version.',
    evidenceNeeds: ['A tested voice session with each affected platform.', 'Recorded input and output device settings.', 'A repeatable result for every proposed fix.'],
    relatedSlugs: ['troubleshooting', 'multiplayer'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting/crossplay-switch-2', title: 'Big Walk Crossplay on Switch 2 — Verification in Progress', h1: 'Big Walk Crossplay on Switch 2',
    description: 'This page is reserved for a current, platform-specific crossplay check.', active: 'puzzles',
    scope: 'No crossplay support is assumed. The page will publish availability, limits, and setup steps only after they are confirmed against the current version and platform guidance.',
    evidenceNeeds: ['Official platform support information or a first-hand cross-platform test.', 'The exact game build and platform versions.', 'A repeatable connection result.'],
    relatedSlugs: ['troubleshooting', 'multiplayer'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting/white-screen-and-crash', title: 'Big Walk White Screen or Crash — Verification in Progress', h1: 'Big Walk White Screen or Crash',
    description: 'A version-specific troubleshooting guide for white screens and crashes is being prepared.', active: 'puzzles',
    scope: 'The eventual checklist will state the exact symptom, platform, and evidence behind each recovery step instead of presenting generic advice as a confirmed Big Walk fix.',
    evidenceNeeds: ['A reproducible start-up or in-session symptom.', 'System and game version details.', 'A tested resolution with a clear result.'],
    relatedSlugs: ['troubleshooting'], illustration: 'map', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'beginner-guide/can-you-play-solo', title: 'Can You Play Big Walk Solo? — Verification in Progress', h1: 'Can You Play Big Walk Solo?',
    description: 'A first-hand answer about solo play in Big Walk is being prepared for the current version.', active: 'beginner',
    scope: 'This page will distinguish launching alone from completing content alone, and will avoid asserting availability or difficulty before a solo session is checked.',
    evidenceNeeds: ['A first-hand solo session in the current version.', 'Clear notes on where solo play is available or blocked.', 'Evidence for any content that materially changes with player count.'],
    relatedSlugs: ['beginner-guide', 'multiplayer/best-group-size'], illustration: 'walker', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
];

export function siteSectionBySlug(slug) {
  return siteSections.find((section) => section.slug === slug);
}

export function guideBySlug(slug) {
  return guides.find((guide) => guide.slug === slug);
}
