export const site = {
  name: 'Big Walk Walkthrough',
  url: 'https://bigwalkwalkthrough.com',
  taxonomy: ['tower', 'area', 'item', 'achievement'],
  puzzleDirectory: {
    title: 'Big Walk Puzzle Guide: Hints, Locations & Solutions',
    h1: 'Big Walk Puzzles Guide by Landmark and Tower',
    description:
      'Browse Big Walk hints and source-checked solutions by tower, item, or location. Original marked screenshots are added after local capture.',
  },
};

export function buildPuzzleDirectoryJsonLd(puzzleGuides) {
  const url = `${site.url}/puzzles`;

  return {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    name: site.puzzleDirectory.h1,
    description: site.puzzleDirectory.description,
    url,
    mainEntity: {
      '@type': 'ItemList',
      name: 'Big Walk puzzle guides',
      numberOfItems: puzzleGuides.length,
      itemListElement: puzzleGuides.map((guide, index) => ({
        '@type': 'ListItem',
        position: index + 1,
        name: guide.h1,
        item: `${site.url}/${guide.slug}`,
      })),
    },
  };
}

export const guides = [
  {
    slug: 'puzzles/green-chair-headphones',
    kind: 'puzzle',
    title: 'Big Walk Sound Check Puzzle: Chair & Headphones Solution',
    h1: 'Big Walk Sound Check Puzzle: Chair and Headphones Solution',
    description:
      'Solve the Big Walk Sound Check puzzle with the chair, six microphones, and headphones. Use a clear two-player callout routine to identify the strongest microphone signal.',
    verificationStatus: 'source_checked',
    verificationLabel: 'Source-checked guide',
    status: 'published',
    evidenceLevel: 'corroborated',
    indexable: true,
    category: 'area',
    tower: 'Yellow Tower area',
    area: 'Sound Check room',
    aliases: ['green chair', 'headphones clue', 'sound check puzzle', 'headphone hell'],
    visualCues: ['chair', 'six microphones', 'headphones'],
    nearbyLandmarks: ['large beige and red archway', 'near the egg hunt puzzle'],
    goal: 'Use the seated player’s audio feedback to identify the strongest microphone without repeating a tested microphone.',
    worldVariants: { twoPlayer: null, threePlayer: null, fourPlus: null },
    prerequisites: [],
    steps: [],
    commonFailures: [],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sourceCheckedAt: '2026-08-09',
    platforms: ['PC two-player source playthrough', 'Big Walk is available on PC, PS5, and Nintendo Switch 2'],
    playerCount: 'Two players are required for the call-and-response method; additional players can observe or relay.',
    evidenceNote: 'This page is based on a published two-player route and the official platform fact sheet. The source describes this as the Sound Check puzzle, not a separate Blue Tower green-platform puzzle.',
    hint: 'One player cannot hear every microphone equally. Make the distance and volume difference do the sorting for you.',
    solutionSteps: [
      { title: 'Set the two roles', body: 'Have one player sit in the chair away from the microphones. The other player stays with the six microphones and speaks into only one microphone at a time.' },
      { title: 'Create a simple callout system', body: 'Use arm raises or another unambiguous signal: the seated player identifies which microphone sounds strongest after each test. Keep a written or spoken list of microphones already used.' },
      { title: 'Test each microphone once', body: 'The microphone player announces its number, then the seated player reports the strongest signal. Do not repeat a microphone after it has been entered into the sequence.' },
      { title: 'Finish the sequence at the puzzle control', body: 'Use the completed no-repeat microphone order at the puzzle’s normal interaction point. If it fails, restart the callout list rather than guessing from memory.' },
    ],
    screenshotRequests: [
      { label: 'Start', description: 'Original capture of the beige-and-red archway and the Sound Check room entrance.' },
      { label: 'Key action', description: 'Original capture showing one player seated with headphones while the partner addresses a numbered microphone.' },
      { label: 'Result', description: 'Original capture of the completed control-panel piece or completion state.' },
    ],
    sources: [
      { title: 'How to Unlock the Tunnels in Big Walk', publisher: 'Screen Hype', url: 'https://www.screenhype.co.uk/how-to-unlock-the-tunnels-in-big-walk/' },
      { title: 'Big Walk press kit and gameplay overview', publisher: 'House House', url: 'https://bigwalk.game/presskit/' },
    ],
    lastVerified: 'Source review on 2026-08-09; original local capture still required',
    updated: '2026-08-09',
    readTime: '4 min read',
    imageAlt: 'original capture target for the Big Walk Sound Check chair and microphones puzzle',
    assetRequirement: 'sound-check-chair-microphones.webp',
    relatedSlugs: ['walkthrough/red-tower-map-room', 'puzzles/4166-1899-coordinates'],
  },
  {
    slug: 'puzzles/purple-things-where-to-use',
    kind: 'puzzle',
    title: 'Where Do Purple Things Go in Big Walk?',
    h1: 'Where Do the Purple Things Go in Big Walk?',
    description:
      'A source-tracked guide to Big Walk purple things. Community reports conflict on their exact endgame use, so this page separates confirmed progress context from claims that still need a local test.',
    verificationStatus: 'evidence_conflict',
    verificationLabel: 'Evidence conflict — not indexed',
    status: 'research',
    evidenceLevel: 'conflicting_reports',
    indexable: false,
    category: 'item',
    tower: 'Late-game completion area',
    area: 'Purple items',
    aliases: ['purple things', 'purple items'],
    visualCues: ['purple items'],
    nearbyLandmarks: ['black tower', 'room up the hill from spawn'],
    goal: 'Avoid wasting purple things while distinguishing reported tower progress from the separate completion-room claim.',
    worldVariants: { twoPlayer: null, threePlayer: null, fourPlus: null },
    prerequisites: [],
    steps: [],
    commonFailures: [],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sourceCheckedAt: '2026-08-09',
    platforms: ['Community reports do not consistently name platform or build'],
    playerCount: 'Unknown — reports come from different groups and must be reproduced in one saved world.',
    evidenceNote: 'Community reports conflict: some say six purple things go into the black tower, while others report completing the black tower with regular red things and saving excess items for a later 15-slot room. This is intentionally not a publishable final answer yet.',
    hint: 'Do not assume the colour itself proves a locked destination. Record what your group has already used before placing another one.',
    solutionSteps: [
      { title: 'Check your progression state first', body: 'Before moving a purple item, note which towers are completed and whether your group has already used red items at the black tower.' },
      { title: 'Treat the black-tower claim as unconfirmed', body: 'A community report says purple things can be placed after the first five towers; another report says regular red things completed that tower before any purple item was found.' },
      { title: 'Preserve evidence for the completion-room claim', body: 'If a post-black-tower room with many slots appears in your world, capture the entrance, slot count, and every item placed before concluding what purple things are for.' },
    ],
    screenshotRequests: [
      { label: 'Start', description: 'Original capture of one purple thing where it is found, including nearby landmark.' },
      { label: 'Key action', description: 'Original capture of the black-tower or later-room slot interface before inserting an item.' },
      { label: 'Result', description: 'Original capture of the resulting unlock, ending state, or unchanged slot count.' },
    ],
    sources: [
      { title: 'Where do the purple “things” go?', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vfxq4r/where_do_the_purple_things_go/' },
      { title: 'Big Walk Guides (unlockables, map locations, items, & more)', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vf9oe3/big_walk_guides_unlockables_map_locations_items/' },
    ],
    lastVerified: 'Source review found unresolved conflict on 2026-08-09',
    updated: '2026-08-09',
    readTime: '3 min read',
    imageAlt: 'original capture target for purple things and their possible placement in Big Walk',
    assetRequirement: 'purple-things-placement-check.webp',
    relatedSlugs: ['puzzles/green-chair-headphones', 'puzzles/4166-1899-coordinates'],
  },
  {
    slug: 'puzzles/4166-1899-coordinates',
    kind: 'puzzle',
    title: 'Big Walk 4166 1899 Coordinates Puzzle Solution',
    h1: 'Big Walk 4166 1899 Coordinates Puzzle: Button Location',
    description:
      'Solve the Big Walk 4166 1899 number puzzle: unlock the map room, read the map or GPS as coordinates, then have one player hold the hidden button while another takes the reward.',
    verificationStatus: 'source_checked',
    verificationLabel: 'Source-checked guide',
    status: 'published',
    evidenceLevel: 'corroborated',
    indexable: true,
    category: 'area',
    tower: 'Red Tower map room',
    area: 'Coordinates',
    aliases: ['4166 1899', '4166-1899'],
    visualCues: ['4166', '1899', 'coordinates'],
    nearbyLandmarks: ['near the beach', 'east and south of the starter hub', 'camouflaged button behind a rock'],
    goal: 'Translate the two four-digit numbers into a map or GPS search, then coordinate two players for the pickup.',
    worldVariants: { twoPlayer: null, threePlayer: null, fourPlus: null },
    prerequisites: [],
    steps: [],
    commonFailures: [],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sourceCheckedAt: '2026-08-09',
    platforms: ['PC source playthrough', 'Big Walk is also released for PS5 and Nintendo Switch 2'],
    playerCount: 'Two players: one holds the hidden button while the other takes the reward.',
    evidenceNote: 'The coordinate interpretation, map-room prerequisite, GPS alternative, and two-player pickup are cross-checked against a current PC guide and the official 2–12-player game description.',
    hint: 'Read the number as two map positions, not as a keypad code. You need a navigation tool before the clue becomes useful.',
    solutionSteps: [
      { title: 'Unlock navigation first', body: 'Complete the Red Tower route to access the Map Room. The map and compass give a grid-based way to interpret the number pair.' },
      { title: 'Read 4166 and 1899 as coordinates', body: 'Use 41 and 18 to find the grid square; the trailing digits narrow the search within it. The reported destination is east and south of the starter hub.' },
      { title: 'Search the rock line for the button', body: 'Look for a small button hidden behind a rock in that part of the map. A GPS is an alternate navigation method if your group has found it.' },
      { title: 'Assign the two-player finish', body: 'One player holds the button while the other returns to the glass-container puzzle to collect the opened reward. Keep a walkie-talkie or clear callout plan ready.' },
    ],
    screenshotRequests: [
      { label: 'Start', description: 'Original capture of the 4166 1899 sign and its nearby prize container.' },
      { label: 'Key action', description: 'Original capture of the map grid or GPS readout at the target search area.' },
      { label: 'Result', description: 'Original capture of the hidden button being held and the opened container.' },
    ],
    sources: [
      { title: 'Big Walk number puzzle: A few small hints and the full solution', publisher: 'PC Gamer', url: 'https://www.pcgamer.com/games/puzzle/big-walk-number-puzzle-4166-1899/' },
      { title: 'Big Walk press kit and gameplay overview', publisher: 'House House', url: 'https://bigwalk.game/presskit/' },
    ],
    lastVerified: 'Source review on 2026-08-09; original local capture still required',
    updated: '2026-08-09',
    readTime: '5 min read',
    imageAlt: 'original capture target for the Big Walk 4166 1899 clue and hidden button',
    assetRequirement: '4166-1899-button-route.webp',
    relatedSlugs: ['puzzles/green-chair-headphones', 'puzzles/purple-things-where-to-use'],
  },
  {
    slug: 'walkthrough/red-tower-map-room',
    kind: 'walkthrough',
    title: 'How to Unlock the Red Tower Map Room in Big Walk',
    h1: 'How to Unlock the Red Tower Map Room in Big Walk',
    description:
      'Unlock the Big Walk Map Room through the Red Tower: complete five nearby puzzles, collect the control-panel pieces, shape the key with the cutters, and open the map-room door.',
    verificationStatus: 'source_checked',
    verificationLabel: 'Source-checked guide',
    status: 'published',
    evidenceLevel: 'corroborated',
    indexable: true,
    category: 'tower',
    tower: 'Red Tower',
    area: 'Red Tower',
    aliases: ['red tower map room', 'map room'],
    visualCues: ['red tower', 'map room'],
    nearbyLandmarks: ['first radio transmitter after the drawbridge', 'long red staircase', 'mountain Red Tower'],
    goal: 'Turn five completed puzzle rewards into the shaped key that opens the Map Room near the start area.',
    worldVariants: { twoPlayer: null, threePlayer: null, fourPlus: null },
    prerequisites: [],
    steps: [],
    commonFailures: [],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sourceCheckedAt: '2026-08-09',
    platforms: ['PC two-player source playthrough', 'Officially supported player count is 2–12'],
    playerCount: 'A two-player route is documented; additional objectives may scale with party size.',
    evidenceNote: 'Two independent current guides agree that Red Tower progress opens the map room. One details the key-cutter sequence; the other links map-room access to five completed puzzle rewards.',
    hint: 'The map room is not opened by finding a code. The route starts with completed puzzle rewards and ends with a physical key you must shape on the way down the mountain.',
    solutionSteps: [
      { title: 'Reach the Red Tower and choose five accessible puzzles', body: 'The reported route uses five nearby puzzle completions to fill the Red Tower control panel. Different groups may choose different puzzles, so use those your party can complete reliably.' },
      { title: 'Collect the control-panel key', body: 'After all five panel pieces are placed, take the key produced by the panel and begin following the marked path down from the tower.' },
      { title: 'Use the cutter trail', body: 'Pass the key through each indicated key cutter in sequence. Follow the arrows after every cut; the last cutter is beside the Map Room staircase.' },
      { title: 'Open the Map Room and take the navigation tools', body: 'Insert the shaped key at the Map Room door. This unlocks the map and compass context needed for coordinate puzzles such as 4166 1899.' },
    ],
    screenshotRequests: [
      { label: 'Start', description: 'Original capture of the Map Room entrance, red staircase, and nearby radio-transmitter landmark.' },
      { label: 'Key action', description: 'Original capture of the Red Tower control panel with five collected pieces or the key-cutter trail.' },
      { label: 'Result', description: 'Original capture of the shaped key in the Map Room door and the opened map room.' },
    ],
    sources: [
      { title: 'How to Unlock the Map Room in Big Walk', publisher: 'Screen Hype', url: 'https://www.screenhype.co.uk/how-to-unlock-the-map-room-in-big-walk/' },
      { title: 'Big Walk number puzzle: A few small hints and the full solution', publisher: 'PC Gamer', url: 'https://www.pcgamer.com/games/puzzle/big-walk-number-puzzle-4166-1899/' },
      { title: 'Big Walk press kit and gameplay overview', publisher: 'House House', url: 'https://bigwalk.game/presskit/' },
    ],
    video: { id: 'G0ez7AP4-GM', title: 'Official Big Walk Gameplay Overview', note: 'This official video provides game context only; it is not presented as evidence for the specific route steps.' },
    lastVerified: 'Source review on 2026-08-09; original local capture still required',
    updated: '2026-08-09',
    readTime: '6 min read',
    imageAlt: 'original capture target for the Big Walk Red Tower map room route',
    assetRequirement: 'red-tower-map-room-route.webp',
    relatedSlugs: ['puzzles/4166-1899-coordinates', 'home'],
  },
  {
    slug: 'walkthrough/crosswalk',
    kind: 'walkthrough',
    title: 'How to Unlock the Crosswalk in Big Walk',
    h1: 'Big Walk Crosswalk Walkthrough: Opening Route',
    description:
      'Unlock the Big Walk Crosswalk with a spoiler-conscious opening route: clear four co-op challenges, return their rewards, resize the gold key, and lower the first bridge.',
    verificationStatus: 'source_checked',
    verificationLabel: 'Source-checked opening route',
    status: 'published',
    evidenceLevel: 'corroborated',
    indexable: true,
    category: 'opening route',
    tower: 'Opening area',
    area: 'Crosswalk',
    aliases: ['crosswalk', 'unlock crosswalk', 'opening bridge', 'first bridge'],
    visualCues: ['raised red drawbridge', 'beach control platform', 'gold key', 'four covered reward slots'],
    nearbyLandmarks: ['tutorial beach', 'customisation structure', 'first mountain slope'],
    goal: 'Complete the four challenges available before the raised Crosswalk, load their rewards into the beach control, resize the gold key, and use it at the bridge lock.',
    routeSummary: [
      'Inspect the beach-side control platform',
      'Clear the four nearby co-op challenges',
      'Return all four red rewards to the control',
      'Release and resize the gold key',
      'Use the finished key at the Crosswalk lock',
    ],
    worldVariants: {
      twoPlayer: 'Split each remote or separated task into a stationary role and a runner or builder.',
      threePlayer: 'Use the third player to relay descriptions, carry pieces, or cover an extra active input shown by the session.',
      fourPlus: 'Assign one player to each active station shown in the selected world and keep one clear caller for timed inputs.',
    },
    prerequisites: ['Finish the tutorial', 'Keep the group on the beach side of the raised Crosswalk'],
    steps: [],
    commonFailures: [
      { problem: 'A challenge gives no reward', fix: 'Repeat that interaction with clearly assigned roles and confirm the active player, control, or order before leaving the landmark.' },
      { problem: 'The remote objective closes', fix: 'Send the holder back to the telescope-side control and keep it active until the runner confirms the pickup.' },
      { problem: 'The symbol submission is rejected', fix: 'Recheck the current displays from first to last and correct the first mismatch; do not reuse a sequence from another session.' },
      { problem: 'The scaffold controls do not register', fix: 'Return everyone to their active station, agree on one countdown, and shorten the interval between inputs.' },
      { problem: 'The group loses the key route', fix: 'Return to the last cutter used and wait for its direction indicator to settle before moving on.' },
    ],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sourceCheckedAt: '2026-08-09',
    platforms: ['PC route source', 'Big Walk is also released for PS5 and Nintendo Switch 2'],
    playerCount: 'Use at least two players. Active inputs can increase with the world size selected for the session.',
    evidenceNote: 'The opening route order and interaction logic are source-checked against a current guide. Official Big Walk material supports the co-op and world-size context, but the site still needs its own current-version captures before describing this as first-hand verified.',
    hint: 'Treat the beach control as your checklist. The raised bridge opens only after the nearby rewards return to that control and the oversized key has followed its marked resizing route.',
    solutionSteps: [
      { title: 'Read the beach control before splitting up', body: 'Use the four covered slots and oversized key as the group checklist. Stay on the tutorial side of the raised bridge until every nearby reward has been returned.' },
      { title: 'Reach the high crane control together', body: 'Look for the yellow crane near the opening slope. Build enough height with your group for the upper player to use the raised control, then collect the reward that appears.' },
      { title: 'Split the telescope job into holder and runner', body: 'Leave one player at the viewing platform to maintain the active control while a second player follows the indicated line toward the remote objective. Keep the control held until the runner confirms the pickup.' },
      { title: 'Describe the symbol sequence instead of guessing it', body: 'At the small blue structure, place one reader inside and one builder outside. Read the active displays in order and reproduce that order with the available pieces; treat any visible sample as session-specific.' },
      { title: 'Coordinate the scaffold controls with one countdown', body: 'Assign players to the active controls shown by the current world. Use a short countdown and restart cleanly if the inputs do not register instead of pressing at random.' },
      { title: 'Return the rewards and release the oversized key', body: 'Bring every red reward back to the beach control and use the matching panel interactions to load the slots. Take the gold key only after the control has accepted the full set.' },
      { title: 'Follow each cutter handoff to the bridge lock', body: 'The first key is too large for the Crosswalk. Use the nearby cutter, read the direction shown after each cut, and follow that handoff until the key fits the grey lock beside the raised bridge.' },
    ],
    screenshotRequests: [
      { label: 'Start', description: 'Original capture of the beach control platform and the raised Crosswalk in the same opening route.' },
      { label: 'Co-op check', description: 'Original capture of one opening challenge with the active player roles clearly visible.' },
      { label: 'Result', description: 'Original capture of the resized gold key at the Crosswalk lock and the lowered bridge.' },
    ],
    sources: [
      { title: 'Big Walk Crosswalk Puzzles — Opening Solutions', publisher: 'Big Walk Wiki', url: 'https://big-walkwiki.wiki/puzzles/crosswalk' },
      { title: 'Big Walk FAQ', publisher: 'House House', url: 'https://bigwalk.game/faq/' },
    ],
    lastVerified: 'Source review on 2026-08-09; original local capture still required',
    updated: '2026-08-09',
    readTime: '8 min read',
    imageAlt: 'original capture target for the Big Walk Crosswalk opening route and bridge key',
    assetRequirement: 'crosswalk-opening-route.webp',
    relatedSlugs: ['walkthrough/red-tower-map-room', 'puzzles'],
  },
];

export const siteSections = [
  {
    slug: 'beginner-guide', title: 'Big Walk Beginner Guide — Verification in Progress', h1: 'Big Walk Beginner Guide',
    description: 'A first-hand Big Walk beginner guide is being prepared for the current version.', active: 'beginner',
    scope: 'The finished guide will explain the opening loop, how to preserve discovery, and where a verified reference can help without presenting guesses as gameplay facts.',
    evidenceNeeds: ['A complete first-hand opening session.', 'Version-checked notes for every beginner recommendation.', 'Original screenshots where visual orientation matters.'],
    relatedSlugs: ['beginner-guide/can-you-play-solo', 'puzzles'], illustration: 'walker', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'achievements', title: 'Big Walk Achievements and Trophies — Verification in Progress', h1: 'Big Walk Achievements and Trophies',
    description: 'A verified Big Walk achievements reference is being prepared with first-hand requirements and annotated evidence.', active: 'achievements',
    scope: 'Individual achievement pages will only be created after a hard requirement has been verified and the page can offer more than a title or recycled description.',
    evidenceNeeds: ['A first-hand completion record for each achievement.', 'The requirement and platform checked against the current version.', 'Screenshots only where they clarify a condition or location.'],
    relatedSlugs: ['puzzles'], illustration: 'trophy', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer/best-group-size', title: 'Best Big Walk Group Size — Verification in Progress', h1: 'What Is the Best Group Size in Big Walk?',
    description: 'A first-hand comparison of Big Walk group sizes is being prepared.', active: 'multiplayer',
    scope: 'The finished comparison will distinguish directly observed communication and exploration differences by group size, instead of treating community preference as a universal answer.',
    evidenceNeeds: ['Comparable first-hand sessions at more than one group size.', 'The tested version and platform for every session.', 'Notes that separate observed differences from player preference.'],
    relatedSlugs: ['multiplayer', 'beginner-guide/can-you-play-solo'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'puzzles/purple-challenges',
    title: 'Purple Challenges in Big Walk — Verification Tracker',
    h1: 'Purple Challenges: Verification Tracker',
    description: 'A dedicated tracker for purple challenge reports in Big Walk. The total, rewards, and player-count differences will be added only after first-hand verification.',
    active: 'puzzles',
    scope: 'This page will keep the purple challenge cluster in one place: how to recognise a reported challenge, the evidence needed to distinguish it from a visual lookalike, and links to verified individual guides when they exist.',
    evidenceNeeds: ['First-hand captures showing each distinct purple challenge.', 'Version and platform recorded for every observation.', 'Repeatable notes for any player-count or reward difference.'],
    relatedSlugs: ['puzzles/purple-things-where-to-use', 'puzzles/green-chair-headphones'],
    illustration: 'map',
    status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'walkthrough', title: 'Big Walk Walkthroughs — Verification in Progress', h1: 'Big Walk Walkthroughs',
    description: 'A route-based walkthrough hub for Big Walk. Only first-hand, version-checked routes will be added.', active: 'walkthrough',
    scope: 'Use this hub to reach verified area walkthroughs. It intentionally does not invent routes, unlock conditions, or rewards before those details are observed.',
    evidenceNeeds: ['A complete first-hand route recording.', 'Landmark screenshots that can be independently matched.', 'A current-version check of all prerequisites and outcomes.'],
    relatedSlugs: ['walkthrough/red-tower-map-room', 'puzzles'], illustration: 'map', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer', title: 'Big Walk Multiplayer & Saves — Verification in Progress', h1: 'Big Walk Multiplayer and Saves',
    description: 'A single hub for first-hand Big Walk multiplayer, hosting, save, and connection notes.', active: 'multiplayer',
    scope: 'This hub separates questions about group play, hosting and saves, finding players, and reconnecting after a disconnect so evidence can be updated without blending different behaviours together.',
    evidenceNeeds: ['A controlled multiplayer session with the tested game version.', 'Host and joiner observations recorded separately.', 'Platform and save-state evidence for each conclusion.'],
    relatedSlugs: ['multiplayer/best-group-size', 'multiplayer/hosting-and-saves', 'multiplayer/transfer-save-to-new-host', 'multiplayer/how-to-find-players'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer/hosting-and-saves', title: 'Big Walk Hosting and Saves — Verification in Progress', h1: 'Big Walk Hosting and Saves',
    description: 'A first-hand reference for hosting, joining, leaving, and save behaviour in Big Walk is being prepared.', active: 'multiplayer',
    scope: 'The finished page will distinguish host behaviour from joiner behaviour and document only save handling that can be reproduced in the current version.',
    evidenceNeeds: ['A host session and a separate joiner session.', 'Observed save state before and after leaving.', 'Original screenshots or recordings of the relevant menus and prompts.'],
    relatedSlugs: ['multiplayer', 'multiplayer/transfer-save-to-new-host', 'troubleshooting/cant-rejoin-after-disconnect'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer/transfer-save-to-new-host', title: 'Transfer a Big Walk Save to a New Host — Verification in Progress', h1: 'Transfer a Big Walk Save to a New Host',
    description: 'This page is reserved for a verified save-transfer workflow, if the current game version supports one.', active: 'multiplayer',
    scope: 'No transfer path is claimed here yet. Once tested, the guide will state the exact supported conditions, platform limits, and recovery advice.',
    evidenceNeeds: ['A repeatable transfer test from the original host to a new host.', 'The exact platform and game version.', 'A before-and-after record that confirms what progress is preserved.'],
    relatedSlugs: ['multiplayer', 'multiplayer/hosting-and-saves'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer/how-to-find-players', title: 'Find Big Walk Players — Verification in Progress', h1: 'How to Find Big Walk Players',
    description: 'A curated, safety-conscious list of active ways to find Big Walk players will be added after sources are checked.', active: 'multiplayer',
    scope: 'The finished page will link to official or clearly identified community spaces and explain what has been checked, instead of implying that a particular group is active.',
    evidenceNeeds: ['An official community or developer-listed contact point.', 'A date-checked community source where activity can be observed.', 'A review of safety and moderation expectations before linking.'],
    relatedSlugs: ['multiplayer', 'multiplayer/best-group-size'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting', title: 'Big Walk Troubleshooting — Verification in Progress', h1: 'Big Walk Troubleshooting',
    description: 'A diagnostic hub for reproducible Big Walk connection, voice, cross-play, and startup problems.', active: 'help',
    scope: 'Each troubleshooting topic will remain separate so reports for one platform or symptom are not mistakenly applied to every player.',
    evidenceNeeds: ['A reproducible issue report with platform and game version.', 'A confirmed resolution or a clearly labelled workaround.', 'A source or first-hand record for every technical recommendation.'],
    relatedSlugs: ['troubleshooting/cant-rejoin-after-disconnect', 'troubleshooting/voice-chat-not-working', 'troubleshooting/crossplay-switch-2', 'troubleshooting/white-screen-and-crash'], illustration: 'map', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting/cant-rejoin-after-disconnect', title: 'Cannot Rejoin Big Walk After a Disconnect — Verification in Progress', h1: 'Cannot Rejoin After a Disconnect',
    description: 'A reproducible diagnosis for Big Walk rejoin failures is being prepared.', active: 'help',
    scope: 'The completed guide will separate a temporary connection interruption from an unsupported session state and will name the tested platform and version.',
    evidenceNeeds: ['Steps that reproduce the rejoin failure.', 'Host and joiner observations.', 'A tested result for each proposed recovery step.'],
    relatedSlugs: ['troubleshooting', 'multiplayer/hosting-and-saves'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting/voice-chat-not-working', title: 'Big Walk Voice Chat Not Working — Verification in Progress', h1: 'Big Walk Voice Chat Not Working',
    description: 'A platform-specific Big Walk voice chat diagnostic is being prepared from reproducible tests.', active: 'help',
    scope: 'The completed guide will list only settings, permissions, and recovery steps that were tested on the named platform and game version.',
    evidenceNeeds: ['A tested voice session with each affected platform.', 'Recorded input and output device settings.', 'A repeatable result for every proposed fix.'],
    relatedSlugs: ['troubleshooting', 'multiplayer'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting/crossplay-switch-2', title: 'Big Walk Crossplay on Switch 2 — Verification in Progress', h1: 'Big Walk Crossplay on Switch 2',
    description: 'This page is reserved for a current, platform-specific crossplay check.', active: 'help',
    scope: 'No crossplay support is assumed. The page will publish availability, limits, and setup steps only after they are confirmed against the current version and platform guidance.',
    evidenceNeeds: ['Official platform support information or a first-hand cross-platform test.', 'The exact game build and platform versions.', 'A repeatable connection result.'],
    relatedSlugs: ['troubleshooting', 'multiplayer'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting/white-screen-and-crash', title: 'Big Walk White Screen or Crash — Verification in Progress', h1: 'Big Walk White Screen or Crash',
    description: 'A version-specific troubleshooting guide for white screens and crashes is being prepared.', active: 'help',
    scope: 'The eventual checklist will state the exact symptom, platform, and evidence behind each recovery step instead of presenting generic advice as a confirmed Big Walk fix.',
    evidenceNeeds: ['A reproducible start-up or in-session symptom.', 'System and game version details.', 'A tested resolution with a clear result.'],
    relatedSlugs: ['troubleshooting'], illustration: 'map', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'beginner-guide/can-you-play-solo', title: 'Can You Play Big Walk Solo? — Verification in Progress', h1: 'Can You Play Big Walk Solo?',
    description: 'A first-hand answer about solo play in Big Walk is being prepared for the current version.', active: 'beginner',
    scope: 'This page will distinguish launching alone from completing content alone, and will avoid asserting availability or difficulty before a solo session is checked.',
    evidenceNeeds: ['A first-hand solo session in the current version.', 'Clear notes on where solo play is available or blocked.', 'Evidence for any content that materially changes with player count.'],
    relatedSlugs: ['beginner-guide', 'multiplayer/best-group-size'], illustration: 'walker', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
];

export function siteSectionBySlug(slug) {
  return siteSections.find((section) => section.slug === slug);
}

export function guideBySlug(slug) {
  return guides.find((guide) => guide.slug === slug);
}
