import { beginnerGuideContent } from './beginner-guide-content.mjs';

export const site = {
  name: 'Big Walk Walkthrough',
  url: 'https://bigwalkwalkthrough.com',
  taxonomy: ['tower', 'area', 'item', 'achievement'],
  puzzleDirectory: {
    title: 'Big Walk Puzzle Guide: Hints, Locations & Solutions',
    h1: 'Big Walk Puzzles Guide by Landmark and Tower',
    description:
      'Browse Big Walk hints and source-checked solutions by tower, item, or location. Original marked screenshots are added after local capture.',
  },
};

export function buildPuzzleDirectoryJsonLd(puzzleGuides) {
  const url = `${site.url}/puzzles`;

  return {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    name: site.puzzleDirectory.h1,
    description: site.puzzleDirectory.description,
    url,
    mainEntity: {
      '@type': 'ItemList',
      name: 'Big Walk puzzle guides',
      numberOfItems: puzzleGuides.length,
      itemListElement: puzzleGuides.map((guide, index) => ({
        '@type': 'ListItem',
        position: index + 1,
        name: guide.h1,
        item: `${site.url}/${guide.slug}`,
      })),
    },
  };
}

export const guides = [
  {
    slug: 'puzzles/green-chair-headphones',
    kind: 'puzzle',
    title: 'Big Walk Sound Check Puzzle: Chair & Headphones Solution',
    h1: 'Big Walk Sound Check Puzzle: Chair and Headphones Solution',
    description:
      'Solve the Big Walk Sound Check puzzle with the chair, six microphones, and headphones. Use a clear two-player callout routine to identify the strongest microphone signal.',
    verificationStatus: 'source_checked',
    verificationLabel: 'Source-checked guide',
    status: 'published',
    evidenceLevel: 'corroborated',
    indexable: true,
    category: 'area',
    tower: 'Yellow Tower area',
    area: 'Sound Check room',
    aliases: ['green chair', 'headphones clue', 'sound check puzzle', 'headphone hell'],
    visualCues: ['chair', 'six microphones', 'headphones'],
    nearbyLandmarks: ['large beige and red archway', 'near the egg hunt puzzle'],
    goal: 'Use the seated player’s audio feedback to identify the strongest microphone without repeating a tested microphone.',
    worldVariants: { twoPlayer: null, threePlayer: null, fourPlus: null },
    prerequisites: [],
    steps: [],
    commonFailures: [],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sourceCheckedAt: '2026-08-09',
    platforms: ['PC two-player source playthrough', 'Big Walk is available on PC, PS5, and Nintendo Switch 2'],
    playerCount: 'Two players are required for the call-and-response method; additional players can observe or relay.',
    evidenceNote: 'This page is based on a published two-player route and the official platform fact sheet. The source describes this as the Sound Check puzzle, not a separate Blue Tower green-platform puzzle.',
    hint: 'One player cannot hear every microphone equally. Make the distance and volume difference do the sorting for you.',
    solutionSteps: [
      { title: 'Set the two roles', body: 'Have one player sit in the chair away from the microphones. The other player stays with the six microphones and speaks into only one microphone at a time.' },
      { title: 'Create a simple callout system', body: 'Use arm raises or another unambiguous signal: the seated player identifies which microphone sounds strongest after each test. Keep a written or spoken list of microphones already used.' },
      { title: 'Test each microphone once', body: 'The microphone player announces its number, then the seated player reports the strongest signal. Do not repeat a microphone after it has been entered into the sequence.' },
      { title: 'Finish the sequence at the puzzle control', body: 'Use the completed no-repeat microphone order at the puzzle’s normal interaction point. If it fails, restart the callout list rather than guessing from memory.' },
    ],
    screenshotRequests: [
      { label: 'Start', description: 'Original capture of the beige-and-red archway and the Sound Check room entrance.' },
      { label: 'Key action', description: 'Original capture showing one player seated with headphones while the partner addresses a numbered microphone.' },
      { label: 'Result', description: 'Original capture of the completed control-panel piece or completion state.' },
    ],
    sources: [
      { title: 'How to Unlock the Tunnels in Big Walk', publisher: 'Screen Hype', url: 'https://www.screenhype.co.uk/how-to-unlock-the-tunnels-in-big-walk/' },
      { title: 'Big Walk press kit and gameplay overview', publisher: 'House House', url: 'https://bigwalk.game/presskit/' },
    ],
    lastVerified: 'Source review on 2026-08-09; original local capture still required',
    updated: '2026-08-09',
    readTime: '4 min read',
    imageAlt: 'original capture target for the Big Walk Sound Check chair and microphones puzzle',
    assetRequirement: 'sound-check-chair-microphones.webp',
    relatedSlugs: ['walkthrough/red-tower-map-room', 'puzzles/4166-1899-coordinates'],
  },
  {
    slug: 'puzzles/purple-things-where-to-use',
    kind: 'puzzle',
    title: 'Where Do Purple Things Go in Big Walk?',
    h1: 'Where Do the Purple Things Go in Big Walk?',
    description:
      'A source-tracked guide to Big Walk purple things. Community reports conflict on their exact endgame use, so this page separates confirmed progress context from claims that still need a local test.',
    verificationStatus: 'evidence_conflict',
    verificationLabel: 'Evidence conflict — not indexed',
    status: 'research',
    evidenceLevel: 'conflicting_reports',
    indexable: false,
    category: 'item',
    tower: 'Late-game completion area',
    area: 'Purple items',
    aliases: ['purple things', 'purple items'],
    visualCues: ['purple items'],
    nearbyLandmarks: ['black tower', 'room up the hill from spawn'],
    goal: 'Avoid wasting purple things while distinguishing reported tower progress from the separate completion-room claim.',
    worldVariants: { twoPlayer: null, threePlayer: null, fourPlus: null },
    prerequisites: [],
    steps: [],
    commonFailures: [],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sourceCheckedAt: '2026-08-09',
    platforms: ['Community reports do not consistently name platform or build'],
    playerCount: 'Unknown — reports come from different groups and must be reproduced in one saved world.',
    evidenceNote: 'Community reports conflict: some say six purple things go into the black tower, while others report completing the black tower with regular red things and saving excess items for a later 15-slot room. This is intentionally not a publishable final answer yet.',
    hint: 'Do not assume the colour itself proves a locked destination. Record what your group has already used before placing another one.',
    solutionSteps: [
      { title: 'Check your progression state first', body: 'Before moving a purple item, note which towers are completed and whether your group has already used red items at the black tower.' },
      { title: 'Treat the black-tower claim as unconfirmed', body: 'A community report says purple things can be placed after the first five towers; another report says regular red things completed that tower before any purple item was found.' },
      { title: 'Preserve evidence for the completion-room claim', body: 'If a post-black-tower room with many slots appears in your world, capture the entrance, slot count, and every item placed before concluding what purple things are for.' },
    ],
    screenshotRequests: [
      { label: 'Start', description: 'Original capture of one purple thing where it is found, including nearby landmark.' },
      { label: 'Key action', description: 'Original capture of the black-tower or later-room slot interface before inserting an item.' },
      { label: 'Result', description: 'Original capture of the resulting unlock, ending state, or unchanged slot count.' },
    ],
    sources: [
      { title: 'Where do the purple “things” go?', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vfxq4r/where_do_the_purple_things_go/' },
      { title: 'Big Walk Guides (unlockables, map locations, items, & more)', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vf9oe3/big_walk_guides_unlockables_map_locations_items/' },
    ],
    lastVerified: 'Source review found unresolved conflict on 2026-08-09',
    updated: '2026-08-09',
    readTime: '3 min read',
    imageAlt: 'original capture target for purple things and their possible placement in Big Walk',
    assetRequirement: 'purple-things-placement-check.webp',
    relatedSlugs: ['puzzles/green-chair-headphones', 'puzzles/4166-1899-coordinates'],
  },
  {
    slug: 'puzzles/4166-1899-coordinates',
    kind: 'puzzle',
    title: 'Big Walk 4166, 1899 Puzzle Solution & Button Location',
    h1: 'How to Solve 4166, 1899 in Big Walk',
    description:
      'Solve the Big Walk 4166, 1899 puzzle: unlock the Red Tower Map Room, read the map or GPS, find the hidden button, and collect the reward.',
    verificationStatus: 'source_checked',
    verificationLabel: 'Source-checked guide',
    status: 'published',
    evidenceLevel: 'corroborated',
    indexable: true,
    category: 'area',
    tower: 'Red Tower map room',
    area: 'Coordinates',
    aliases: ['4166 1899', '4166-1899'],
    visualCues: ['4166', '1899', 'coordinates'],
    nearbyLandmarks: ['near the beach', 'east and south of the starter hub', 'camouflaged button behind a rock'],
    goal: 'Translate the two four-digit numbers into a map or GPS search, then coordinate two players for the pickup.',
    directAnswer: '4166, 1899 are map coordinates, not a keypad code. Unlock the Red Tower Map Room, use the paper map and compass or the GPS to reach the target, find the small button behind a rock, then keep one player on the button while another collects the reward at the numbered structure.',
    worldVariants: { twoPlayer: null, threePlayer: null, fourPlus: null },
    prerequisites: [
      { text: 'Bring at least two players: one person must hold the remote button while another collects the reward.' },
      { text: 'Complete the Red Tower route first, then take the map and compass from the Map Room.', href: '/walkthrough/red-tower-map-room', linkLabel: 'Open the Red Tower Map Room walkthrough' },
      { text: 'Carry the paper map and compass together if you are using the Map Room method.' },
      { text: 'Agree on walkie-talkie callouts before splitting between the button and the numbered structure.' },
    ],
    numberConfirmation: {
      heading: 'Confirm the numbers first',
      body: 'The fixed sign on the orange building reads 4166, 1899. Numbers that keep changing on the map or GPS are your live position, not the puzzle answer.',
      disambiguation: 'Searched for 1466 or 3971? Those are usually a misremembered order or a live GPS readout — check the fixed sign on the orange building.',
    },
    roleAssignments: [
      { title: 'Player A', body: 'Stay at the hidden button and keep it pressed. Tell Player B when the reward is open, and remain on the button until they confirm the pickup.' },
      { title: 'Player B', body: 'Return to the orange numbered building and collect the reward while Player A holds the button. Keep voice or walkie-talkie contact active for the entire handoff.' },
    ],
    lostReward: {
      status: 'To verify',
      body: 'Community reports suggest that a dropped reward returns to the puzzle location after reloading the world. This recovery behaviour still needs a first-hand test on the current version.',
    },
    steps: [],
    progressiveHints: [
      { title: 'Hint 1 — Read, do not enter', body: 'The two four-digit numbers are not a keypad combination. They describe a point in the world.' },
      { title: 'Hint 2 — Split each number', body: 'Use 41 and 18 to identify the map grid, then use 66 and 99 to refine the position inside that grid.' },
      { title: 'Hint 3 — Check the back of the rocks', body: 'The destination is east and south of the starter hub. The final interaction is a small button concealed behind a rock.' },
    ],
    navigationMethods: [
      { title: 'Paper map and compass', body: 'Complete the Red Tower route, take the Map Room tools, locate grid 41 by 18, then use 66 and 99 to narrow the exact point. Keep the compass aligned while crossing the rocky ground.' },
      { title: 'GPS alternative', body: 'If your group has found the GPS near the Green Tower, carry it to the matching readout instead of plotting the paper grid. The destination and two-player finish are the same.' },
    ],
    commonFailures: [
      { problem: 'Treating 4166, 1899 as a keypad code', fix: 'Stop searching for an input panel. Split the values into grid and within-grid coordinates.' },
      { problem: 'Searching before unlocking navigation tools', fix: 'Complete the Red Tower Map Room route first, or obtain the GPS, so you can identify the target area reliably.' },
      { problem: 'Using only 41 and 18', fix: 'Those values identify the broad grid. Use 66 and 99 to refine where you search inside it.' },
      { problem: 'Looking only at the front of rocks', fix: 'Circle the grey boulders in the target area; the small button is tucked behind a rock.' },
      { problem: 'Both players wait at the hidden button', fix: 'Leave one player holding the button and send the other back to the 4166, 1899 structure to collect the opened reward.' },
    ],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sourceCheckedAt: '2026-08-10',
    platforms: ['PC source playthrough', 'Big Walk is also released for PS5 and Nintendo Switch 2'],
    playerCount: 'Two players: one holds the hidden button while the other takes the reward.',
    evidenceNote: 'The coordinate interpretation, Map Room prerequisite, GPS alternative, hidden button, and two-player pickup were cross-checked against a current written guide and the supplied 8:33 route video. Original local screenshots are still pending and are clearly labelled below.',
    hint: 'Do not search for a keypad. First unlock a tool that lets you treat the two numbers as a location.',
    solutionSteps: [
      { title: 'Unlock navigation first', body: 'Complete five puzzle rewards for the Red Tower route, shape its key, and open the Map Room. Take the paper map and compass. If your party already has the GPS near the Green Tower, you can use that instead.' },
      { title: 'Find the 41 by 18 map grid', body: 'Read 4166 and 1899 as two coordinates. Use 41 on one map axis and 18 on the other to identify the broad grid square east and south of the starter hub.' },
      { title: 'Refine the point with 66 and 99', body: 'The trailing digits are not disposable. Use 66 and 99 to narrow the target within the 41 by 18 grid rather than sweeping the entire square.' },
      { title: 'Follow the rocky approach and find the button', body: 'Travel to the plotted point and circle the grey rocks. In the supplied video, a blue rail or pipe and a distant red structure are visible on the final approach. The small yellow-and-red button is hidden behind a grey boulder.' },
      { title: 'Split the final two-player job', body: 'Leave one player holding the hidden button. The second player returns to the orange 4166, 1899 structure and collects the opened reward. Use walkie-talkies to confirm when the button is held.' },
    ],
    screenshotRequests: [
      { label: 'Clue and reward', description: 'Original capture of the orange 4166, 1899 structure, number sign, and nearby reward container.' },
      { label: 'Map reading', description: 'Original marked capture showing the 41 by 18 grid and the 66 by 99 refinement, or the matching GPS readout.' },
      { label: 'Final approach', description: 'Original capture of the target rock line with safe route landmarks marked.' },
      { label: 'Button and result', description: 'Original capture of the hidden button behind the rock plus the opened reward at the numbered structure.' },
    ],
    sources: [
      { title: 'Big Walk number puzzle: A few small hints and the full solution', publisher: 'PC Gamer', url: 'https://www.pcgamer.com/games/puzzle/big-walk-number-puzzle-4166-1899/' },
      { title: 'How to solve 4166, 1899 Big Walk Puzzle Solution | Button Location', publisher: 'MonkeyKingHero', url: 'https://www.youtube.com/watch?v=-oTJVxglRn4' },
      { title: 'Big Walk press kit and gameplay overview', publisher: 'House House', url: 'https://bigwalk.game/presskit/' },
    ],
    video: {
      id: '-oTJVxglRn4',
      title: '4166, 1899 route and button location video',
      note: 'MonkeyKingHero’s 8:33 route demonstration; the button-location segment begins at 7:00. It is embedded as supporting evidence, and its frames are not republished as site screenshots.',
      startAt: 420,
      watchUrl: 'https://www.youtube.com/watch?v=-oTJVxglRn4&t=420s',
    },
    lastVerified: 'Written guide and supplied route video cross-checked on 2026-08-10; original local captures pending',
    updated: '2026-08-10',
    readTime: '7 min read',
    imageAlt: 'original capture target for the Big Walk 4166 1899 clue and hidden button',
    assetRequirement: '4166-1899-button-route.webp',
    relatedSlugs: ['walkthrough/red-tower-map-room', 'walkthrough/crosswalk'],
  },
  {
    slug: 'walkthrough/red-tower-map-room',
    kind: 'walkthrough',
    title: 'How to Unlock the Red Tower Map Room in Big Walk',
    h1: 'How to Unlock the Red Tower Map Room in Big Walk',
    description:
      'Unlock the Big Walk Map Room through the Red Tower: complete five nearby puzzles, collect the control-panel pieces, shape the key with the cutters, and open the map-room door.',
    verificationStatus: 'source_checked',
    verificationLabel: 'Source-checked guide',
    status: 'published',
    evidenceLevel: 'corroborated',
    indexable: true,
    category: 'tower',
    tower: 'Red Tower',
    area: 'Red Tower',
    aliases: ['red tower map room', 'map room'],
    visualCues: ['red tower', 'map room'],
    nearbyLandmarks: ['first radio transmitter after the drawbridge', 'long red staircase', 'mountain Red Tower'],
    goal: 'Turn five completed puzzle rewards into the shaped key that opens the Map Room near the start area.',
    worldVariants: { twoPlayer: null, threePlayer: null, fourPlus: null },
    prerequisites: [],
    steps: [],
    commonFailures: [],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sourceCheckedAt: '2026-08-09',
    platforms: ['PC two-player source playthrough', 'Officially supported player count is 2–12'],
    playerCount: 'A two-player route is documented; additional objectives may scale with party size.',
    evidenceNote: 'Two independent current guides agree that Red Tower progress opens the map room. One details the key-cutter sequence; the other links map-room access to five completed puzzle rewards.',
    hint: 'The map room is not opened by finding a code. The route starts with completed puzzle rewards and ends with a physical key you must shape on the way down the mountain.',
    solutionSteps: [
      { title: 'Reach the Red Tower and choose five accessible puzzles', body: 'The reported route uses five nearby puzzle completions to fill the Red Tower control panel. Different groups may choose different puzzles, so use those your party can complete reliably.' },
      { title: 'Collect the control-panel key', body: 'After all five panel pieces are placed, take the key produced by the panel and begin following the marked path down from the tower.' },
      { title: 'Use the cutter trail', body: 'Pass the key through each indicated key cutter in sequence. Follow the arrows after every cut; the last cutter is beside the Map Room staircase.' },
      { title: 'Open the Map Room and take the navigation tools', body: 'Insert the shaped key at the Map Room door. This unlocks the map and compass context needed for coordinate puzzles such as 4166 1899.' },
    ],
    screenshotRequests: [
      { label: 'Start', description: 'Original capture of the Map Room entrance, red staircase, and nearby radio-transmitter landmark.' },
      { label: 'Key action', description: 'Original capture of the Red Tower control panel with five collected pieces or the key-cutter trail.' },
      { label: 'Result', description: 'Original capture of the shaped key in the Map Room door and the opened map room.' },
    ],
    sources: [
      { title: 'How to Unlock the Map Room in Big Walk', publisher: 'Screen Hype', url: 'https://www.screenhype.co.uk/how-to-unlock-the-map-room-in-big-walk/' },
      { title: 'Big Walk number puzzle: A few small hints and the full solution', publisher: 'PC Gamer', url: 'https://www.pcgamer.com/games/puzzle/big-walk-number-puzzle-4166-1899/' },
      { title: 'Big Walk press kit and gameplay overview', publisher: 'House House', url: 'https://bigwalk.game/presskit/' },
    ],
    video: { id: 'G0ez7AP4-GM', title: 'Official Big Walk Gameplay Overview', note: 'This official video provides game context only; it is not presented as evidence for the specific route steps.' },
    lastVerified: 'Source review on 2026-08-09; original local capture still required',
    updated: '2026-08-09',
    readTime: '6 min read',
    imageAlt: 'original capture target for the Big Walk Red Tower map room route',
    assetRequirement: 'red-tower-map-room-route.webp',
    relatedSlugs: ['puzzles/4166-1899-coordinates', 'walkthrough/blue-tower-train', 'home'],
  },
  {
    slug: 'walkthrough/blue-tower-train',
    kind: 'walkthrough',
    title: 'How to Start the Train in Big Walk | Big Ride Achievement',
    absoluteTitle: true,
    h1: 'How to Start the Train in Big Walk',
    description:
      'Start the train in Big Walk by filling the Blue Tower roof slots, shaping its key, and activating the station for the Big Ride achievement.',
    verificationStatus: 'source_checked',
    verificationLabel: 'Source-checked guide',
    status: 'published',
    evidenceLevel: 'corroborated',
    indexable: true,
    category: 'tower route',
    tower: 'Blue Tower',
    area: 'Train network',
    aliases: ['start the train', 'unlock the train', 'Big Ride achievement', 'Blue Tower train'],
    visualCues: ['blue tower', 'five rooftop slots', 'blue key cutters', 'red train tracks'],
    nearbyLandmarks: ['Blue Tower roof', 'key cutters around the tower base', 'nearby train station'],
    goal: 'Place five red puzzle rewards in the Blue Tower, shape the released key through all five cutters, use it at the nearby station building, and board the train.',
    directAnswer: 'The train is not started from the platform first. Put five red puzzle rewards into the open slots on the Blue Tower roof, take the released key through all five blue cutters, then insert the finished key in the nearby station building. Board the arriving train to unlock Big Ride.',
    routeSummary: [
      'Bring five red puzzle rewards to the Blue Tower',
      'Place all five rewards in the open roof slots',
      'Shape the released key through five blue cutters',
      'Use the finished key in the nearby station building',
      'Wait at the platform and board for Big Ride',
    ],
    worldVariants: { twoPlayer: null, threePlayer: null, fourPlus: null },
    prerequisites: [
      'Lower the opening Crosswalk so the group can reach the wider island and Blue Tower.',
      'Collect five red rewards from completed puzzles. They do not have to come from a fixed set of Blue Tower puzzles.',
      'Keep the same host and saved world that holds the tower progress.',
    ],
    steps: [],
    commonFailures: [
      { problem: 'The roof key does not appear', fix: 'Check every open roof slot. The tower accepts five red puzzle rewards; a nearby puzzle list is a convenient route, not a fixed requirement.' },
      { problem: 'You collected the key but the trains remain still', fix: 'Start with the blue cutter outside the tower base, then follow each cutter marker until the key has passed through all five machines.' },
      { problem: 'The finished key does not start the network', fix: 'Follow the final marker and nearby red tracks to the station building, then insert the shaped key into its keyhole. Carrying the key to the platform is not enough.' },
      { problem: 'No train is at the platform', fix: 'Check the station schedule and wait beside the active track. Once the network is running, trains travel a loop and may be between stations.' },
      { problem: 'Big Ride does not unlock after activation', fix: 'Activation and the achievement are separate moments. Wait for the train to stop, jump aboard, and ride it.' },
    ],
    recoveryHeading: "If the train doesn't come",
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sourceCheckedAt: '2026-08-10',
    platforms: ['PC source playthroughs', 'Big Walk is also released for PS5 and Nintendo Switch 2'],
    playerCount: 'Two to twelve players are supported. The host chooses a 2-player, 3-player, or 4+ world, so individual puzzle layouts can vary; the checked train guides do not document every world-size variant separately.',
    evidenceNote: 'Quest Daily, Insider Gaming, Destructoid, and a current community guide agree on the five Blue Tower rewards, key-cutting route, train activation, and boarding outcome. Quest Daily and the community guide also clarify that any red puzzle rewards qualify; the nearby puzzles are a suggested route rather than mandatory objectives. Original local captures are still pending.',
    hint: 'The train is not started at the platform first. Complete the Blue Tower reward-and-key route before waiting at a station.',
    solutionSteps: [
      { title: 'Bring five red puzzle rewards to the Blue Tower', body: 'Cross the opening bridge and find the Blue Tower. Collect five red rewards from completed puzzles. You can use nearby challenges for convenience, but the checked sources do not require one fixed set of five puzzles.' },
      { title: 'Fill the five slots on the roof', body: 'Carry the rewards upstairs and place one in each open case on the Blue Tower roof. The tower releases the train key only after all five slots are filled.' },
      { title: 'Shape the key through all five cutters', body: 'Take the key to the first blue cutter outside the tower base. After each cut, read the direction marker on the pillar and carry the key to the next machine until all five cutters have shaped it.' },
      { title: 'Use the finished key at the station building', body: 'Follow the final marker and the nearby red train tracks to the station building. Insert the finished key into its keyhole to activate the island-wide train network.' },
      { title: 'Board the train for Big Ride', body: 'Check the station schedule and wait at the platform. When the train arrives and stops, jump aboard and ride it to unlock the Big Ride achievement.' },
    ],
    screenshotRequests: [
      { label: 'Blue Tower roof slots', description: 'Original capture of the five open reward cases on the Blue Tower roof before the final red reward is placed.' },
      { label: 'Train key and cutter route', description: 'Original capture of the released key at the first blue cutter, with the next direction marker visible.' },
      { label: 'Station activation', description: 'Original capture of the finished key entering the station-building keyhole, with the platform or arriving train in view.' },
    ],
    sources: [
      { title: 'Guide: How To Unlock The Train In Big Walk', publisher: 'Quest Daily', url: 'https://questdaily.com.au/walkthrough/guide-how-to-unlock-the-train-in-big-walk/' },
      { title: 'How to Start The Train in Big Walk — Big Ride Achievement, Explained', publisher: 'Insider Gaming', url: 'https://insider-gaming.com/big-walk-unlock-train-big-ride-achievement/' },
      { title: 'How to unlock and activate the train in Big Walk', publisher: 'Destructoid', url: 'https://www.destructoid.com/how-to-unlock-and-activate-the-train-in-big-walk/' },
      { title: 'Big Walk Guides — unlockables, map locations, items, and more', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vf9oe3/big_walk_guides_unlockables_map_locations_items/' },
      { title: 'Big Walk FAQ', publisher: 'House House and Panic', url: 'https://games.panic.com/bigwalk/faq/' },
    ],
    lastVerified: 'Four current route sources cross-checked on 2026-08-10; original local captures pending',
    updated: '2026-08-10',
    readTime: '6 min read',
    imageAlt: 'original capture target for the Big Walk Blue Tower train key and station activation route',
    assetRequirement: 'blue-tower-train-key-route.webp',
    relatedSlugs: ['walkthrough/red-tower-map-room', 'walkthrough/crosswalk'],
  },
  {
    slug: 'walkthrough/crosswalk',
    kind: 'walkthrough',
    title: 'How to Unlock the Crosswalk in Big Walk',
    h1: 'Big Walk Crosswalk Walkthrough: Opening Route',
    description:
      'Unlock the Big Walk Crosswalk with a spoiler-conscious opening route: clear four co-op challenges, return their rewards, resize the gold key, and lower the first bridge.',
    verificationStatus: 'source_checked',
    verificationLabel: 'Source-checked opening route',
    status: 'published',
    evidenceLevel: 'corroborated',
    indexable: true,
    category: 'opening route',
    tower: 'Opening area',
    area: 'Crosswalk',
    aliases: ['crosswalk', 'unlock crosswalk', 'opening bridge', 'first bridge'],
    visualCues: ['raised red drawbridge', 'beach control platform', 'gold key', 'four covered reward slots'],
    nearbyLandmarks: ['tutorial beach', 'customisation structure', 'first mountain slope'],
    goal: 'Complete the four challenges available before the raised Crosswalk, load their rewards into the beach control, resize the gold key, and use it at the bridge lock.',
    routeSummary: [
      'Inspect the beach-side control platform',
      'Clear the four nearby co-op challenges',
      'Return all four red rewards to the control',
      'Release and resize the gold key',
      'Use the finished key at the Crosswalk lock',
    ],
    worldVariants: {
      twoPlayer: 'Split each remote or separated task into a stationary role and a runner or builder.',
      threePlayer: 'Use the third player to relay descriptions, carry pieces, or cover an extra active input shown by the session.',
      fourPlus: 'Assign one player to each active station shown in the selected world and keep one clear caller for timed inputs.',
    },
    prerequisites: ['Finish the tutorial', 'Keep the group on the beach side of the raised Crosswalk'],
    steps: [],
    commonFailures: [
      { problem: 'A challenge gives no reward', fix: 'Repeat that interaction with clearly assigned roles and confirm the active player, control, or order before leaving the landmark.' },
      { problem: 'The remote objective closes', fix: 'Send the holder back to the telescope-side control and keep it active until the runner confirms the pickup.' },
      { problem: 'The symbol submission is rejected', fix: 'Recheck the current displays from first to last and correct the first mismatch; do not reuse a sequence from another session.' },
      { problem: 'The scaffold controls do not register', fix: 'Return everyone to their active station, agree on one countdown, and shorten the interval between inputs.' },
      { problem: 'The group loses the key route', fix: 'Return to the last cutter used and wait for its direction indicator to settle before moving on.' },
    ],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sourceCheckedAt: '2026-08-09',
    platforms: ['PC route source', 'Big Walk is also released for PS5 and Nintendo Switch 2'],
    playerCount: 'Use at least two players. Active inputs can increase with the world size selected for the session.',
    evidenceNote: 'The opening route order and interaction logic are source-checked against a current guide. Official Big Walk material supports the co-op and world-size context, but the site still needs its own current-version captures before describing this as first-hand verified.',
    hint: 'Treat the beach control as your checklist. The raised bridge opens only after the nearby rewards return to that control and the oversized key has followed its marked resizing route.',
    solutionSteps: [
      { title: 'Read the beach control before splitting up', body: 'Use the four covered slots and oversized key as the group checklist. Stay on the tutorial side of the raised bridge until every nearby reward has been returned.' },
      { title: 'Reach the high crane control together', body: 'Look for the yellow crane near the opening slope. Build enough height with your group for the upper player to use the raised control, then collect the reward that appears.' },
      { title: 'Split the telescope job into holder and runner', body: 'Leave one player at the viewing platform to maintain the active control while a second player follows the indicated line toward the remote objective. Keep the control held until the runner confirms the pickup.' },
      { title: 'Describe the symbol sequence instead of guessing it', body: 'At the small blue structure, place one reader inside and one builder outside. Read the active displays in order and reproduce that order with the available pieces; treat any visible sample as session-specific.' },
      { title: 'Coordinate the scaffold controls with one countdown', body: 'Assign players to the active controls shown by the current world. Use a short countdown and restart cleanly if the inputs do not register instead of pressing at random.' },
      { title: 'Return the rewards and release the oversized key', body: 'Bring every red reward back to the beach control and use the matching panel interactions to load the slots. Take the gold key only after the control has accepted the full set.' },
      { title: 'Follow each cutter handoff to the bridge lock', body: 'The first key is too large for the Crosswalk. Use the nearby cutter, read the direction shown after each cut, and follow that handoff until the key fits the grey lock beside the raised bridge.' },
    ],
    screenshotRequests: [
      { label: 'Start', description: 'Original capture of the beach control platform and the raised Crosswalk in the same opening route.' },
      { label: 'Co-op check', description: 'Original capture of one opening challenge with the active player roles clearly visible.' },
      { label: 'Result', description: 'Original capture of the resized gold key at the Crosswalk lock and the lowered bridge.' },
    ],
    sources: [
      { title: 'Big Walk Crosswalk Puzzles — Opening Solutions', publisher: 'Big Walk Wiki', url: 'https://big-walkwiki.wiki/puzzles/crosswalk' },
      { title: 'Big Walk FAQ', publisher: 'House House', url: 'https://bigwalk.game/faq/' },
    ],
    lastVerified: 'Source review on 2026-08-09; original local capture still required',
    updated: '2026-08-09',
    readTime: '8 min read',
    imageAlt: 'original capture target for the Big Walk Crosswalk opening route and bridge key',
    assetRequirement: 'crosswalk-opening-route.webp',
    relatedSlugs: ['walkthrough/red-tower-map-room', 'puzzles'],
  },
  {
    slug: 'walkthrough/green-room',
    kind: 'walkthrough',
    title: 'Big Walk Green Room Location & How to Open It',
    absoluteTitle: true,
    h1: 'How to Find and Open the Green Room in Big Walk',
    description: 'This is NOT the green chair and headphones (Sound Check) puzzle. This research page tracks the separate green room, its reported entrance, and its possible 15-slot purpose without presenting disputed mechanics as fact.',
    verificationStatus: 'evidence_conflict',
    verificationLabel: 'Evidence conflict — research page, not indexed',
    status: 'research',
    evidenceLevel: 'conflicting_reports',
    indexable: false,
    category: 'area',
    tower: 'Green Room research',
    area: 'Reported post-game green room',
    aliases: ['green room', 'green bunker', '15-slot room'],
    visualCues: ['green exterior or walls (reported)', '15 item slots (reported)', 'button behind the structure (reported)'],
    nearbyLandmarks: ['uphill from spawn (community report)', 'Map Room route context'],
    goal: 'Separate the reported green completion room from Sound Check, then preserve the unresolved entrance and item-use evidence for a first-hand test.',
    worldVariants: { twoPlayer: null, threePlayer: null, fourPlus: null },
    prerequisites: [],
    steps: [],
    commonFailures: [
      { problem: 'The door does not open', fix: 'To verify: record the world progression state, inspect the reported rear-button area, and avoid assuming a missing item count.' },
      { problem: 'A carried item disappears', fix: 'To verify: note where it was dropped, reload once, and check both the original pickup and reported room locations.' },
      { problem: 'The room or item state changes after reload', fix: 'To verify: capture before-and-after slot counts and the current host save before drawing a recovery conclusion.' },
    ],
    testedPlatforms: [],
    gameVersion: null,
    verifiedAt: null,
    sourceCheckedAt: '2026-08-10',
    platforms: ['Community posts and video comments do not consistently identify platform or game build'],
    playerCount: 'Unknown. The room and its opening condition have not been reproduced first-hand.',
    evidenceNote: 'The green room demand is real, but reports disagree about what red and purple items unlock. The entrance position, rear button, opening condition, item persistence, and 15-slot behaviour remain explicitly unverified.',
    hint: 'If you are looking at a chair and headphones, you are at Sound Check, not the green room tracked on this page.',
    solutionSteps: [
      { title: 'Separate the two green searches', body: 'Use the chair-and-headphones guide for Sound Check. Continue here only if you mean the reported green room or green bunker with item slots.' },
      { title: 'Record the route and entrance before interacting', body: 'Follow either the Map Room route context or a direct route from spawn, but treat the entrance wall and rear-button position as unverified until an original capture confirms them.' },
      { title: 'Preserve the item evidence', body: 'Record the colour and count of every item before placing it. Conflicting reports do not yet prove whether red and purple items are interchangeable.' },
    ],
    greenRoomSections: {
      routes: [
        { title: 'Route A — via the Map Room', body: 'Use the verified Red Tower Map Room route as an orientation anchor, then return toward the spawn-side uphill area. The final turn and entrance position are to be verified.' },
        { title: 'Route B — direct from spawn', body: 'Community comments describe a green bunker or room up the hill from spawn. The exact path, wall, and entry point are to be verified before this becomes a step-by-step route.' },
      ],
      entrance: { title: 'Entrance, wall, and rear button', status: 'Position to be verified', body: 'Reports mention a green structure and a button around the back, but no original site screenshot currently proves the exact wall or button position. Treat every precise entrance claim as position to be verified.' },
      slots: { title: 'What is the 15-slot room for?', status: 'Community-reported', body: 'Players report a room with 15 slots connected to late-game item collection. The slot count and resulting unlock have not been reproduced first-hand for this site.' },
      itemConflict: {
        title: 'Can red and purple items be mixed?',
        status: 'Evidence conflict',
        body: 'One Reddit discussion says purple items belong at the black tower; replies report finishing that tower with regular red items and saving items for a later room. Do not treat either mechanism as confirmed.',
        sources: [
          { title: 'Where do the purple “things” go?', url: 'https://www.reddit.com/r/BigWalk/comments/1vfxq4r/where_do_the_purple_things_go/' },
          { title: 'Big Walk guides: unlockables, map locations and items', url: 'https://www.reddit.com/r/BigWalk/comments/1vf9oe3/big_walk_guides_unlockables_map_locations_items/' },
        ],
      },
      mapTracking: { title: 'Use the Map Room to track missing items', status: 'Community-reported', body: 'Players report using the Map Room to identify uncollected item markers. The exact marker behaviour for purple items and completed objectives still needs a controlled save-state check.' },
      recovery: { title: 'Door, missing items, and reload recovery', status: 'To verify', body: 'If the door stays shut or an item disappears, record the host, save state, and slot count before reloading. Reports of items returning after reload are not yet first-hand verified.' },
    },
    screenshotRequests: [
      { label: 'Disambiguation', description: 'Original capture showing the green room exterior separately from the Sound Check chair-and-headphones room.' },
      { label: 'Entrance', description: 'Original marked capture of the entrance wall and any rear button, with route landmarks visible.' },
      { label: '15-slot evidence', description: 'Original capture of the room before and after item placement, including the full slot count.' },
      { label: 'Recovery test', description: 'Original before-and-after reload captures documenting any returned item or unchanged door state.' },
    ],
    sources: [
      { title: 'Where do the purple “things” go?', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vfxq4r/where_do_the_purple_things_go/' },
      { title: 'Big Walk Guides (unlockables, map locations, items, & more)', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vf9oe3/big_walk_guides_unlockables_map_locations_items/' },
      { title: 'Big Walk True Secret Full Ending', publisher: 'YouTube community discussion', url: 'https://www.youtube.com/watch?v=dkhYnp83s1I' },
    ],
    plannedLinks: ['puzzles/purple-things-where-to-use', 'puzzles/purple-challenges', 'walkthrough/true-ending'],
    lastVerified: 'Conflicting community evidence reviewed on 2026-08-10; entrance and opening condition require first-hand verification',
    updated: '2026-08-10',
    readTime: '6 min read',
    imageAlt: 'original capture target for the reported Big Walk green room entrance and 15-slot interior',
    assetRequirement: 'green-room-entrance-research.webp',
    relatedSlugs: ['walkthrough/red-tower-map-room', 'puzzles/purple-things-where-to-use'],
  },
];

export const siteSections = [
  {
    slug: 'beginner-guide', title: 'Big Walk Beginner Guide — First Session Tips, Saves & Co-op Setup', h1: 'Big Walk Beginner Guide: What to Know Before Your First Walk',
    description: 'A spoiler-light Big Walk beginner guide to choosing a host and world size, protecting your save, communicating in-game, regrouping, and deciding what to do first.', active: 'beginner',
    scope: 'This handbook prepares a new group for its first session without revealing puzzle solutions. Official sources support setup and communication facts; route advice is source-checked, while player tactics stay visibly labelled as community reports.',
    evidenceNeeds: ['A complete first-hand opening session.', 'Version-checked notes for every beginner recommendation.', 'Original screenshots where visual orientation matters.'],
    relatedSlugs: ['beginner-guide/can-you-play-solo', 'multiplayer/hosting-and-saves', 'walkthrough/crosswalk', 'walkthrough/red-tower-map-room', 'troubleshooting/voice-chat-not-working', 'puzzles'], illustration: 'walker', status: 'published', evidenceLevel: 'corroborated', verificationLabel: 'Official facts + source-checked first-session guidance', indexable: true, updated: '2026-08-10',
    beginnerGuide: beginnerGuideContent,
  },
  {
    slug: 'achievements', title: 'Big Walk Achievements and Trophies — Verification in Progress', h1: 'Big Walk Achievements and Trophies',
    description: 'A verified Big Walk achievements reference is being prepared with first-hand requirements and annotated evidence.', active: 'achievements',
    scope: 'Individual achievement pages will only be created after a hard requirement has been verified and the page can offer more than a title or recycled description.',
    evidenceNeeds: ['A first-hand completion record for each achievement.', 'The requirement and platform checked against the current version.', 'Screenshots only where they clarify a condition or location.'],
    relatedSlugs: ['puzzles'], illustration: 'trophy', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer/best-group-size', title: 'Best Big Walk Group Size — Verification in Progress', h1: 'What Is the Best Group Size in Big Walk?',
    description: 'A first-hand comparison of Big Walk group sizes is being prepared.', active: 'multiplayer',
    scope: 'The finished comparison will distinguish directly observed communication and exploration differences by group size, instead of treating community preference as a universal answer.',
    evidenceNeeds: ['Comparable first-hand sessions at more than one group size.', 'The tested version and platform for every session.', 'Notes that separate observed differences from player preference.'],
    relatedSlugs: ['multiplayer', 'beginner-guide/can-you-play-solo'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'puzzles/purple-challenges',
    title: 'Purple Challenges in Big Walk — All 7 Listed with Locations',
    h1: 'All 7 Purple Challenges in Big Walk',
    description: 'Browse the seven purple challenges reported by current player guides, with visual cues, location evidence, transport needs, party notes, and explicit verification labels.',
    active: 'puzzles',
    scope: 'This directory cross-checks a current seven-challenge video guide with community map handles. Map handles are not official in-game names, and uncertain video-to-map matches remain marked rather than guessed.',
    evidenceNeeds: ['First-hand confirmation of the total in a current save.', 'First-hand capture of every reward and completion state.', 'Repeatable notes for player-count differences.'],
    pendingFirstHand: [
      { label: 'Total', value: 'Pending first-hand verification' },
      { label: 'Rewards', value: 'Pending first-hand verification' },
      { label: 'Player-count differences', value: 'Pending first-hand verification' },
    ],
    challenges: [
      {
        name: 'Purple Flag Pole Golf',
        visualCues: 'Purple flagpole, golf ball, route arrow, and a mountain return route.',
        position: 'GamesRef “Cannonball Commute” marker: map x17.044%, y15.235%; elevation 88m.',
        prerequisiteItem: 'Original golf ball carried back from its pickup point (community video).',
        transport: 'Train and drawbridge are shown as transport options in the guide video.',
        playerCount: 'Co-op shown; exact minimum and scaling pending first-hand verification.',
        verificationStatus: 'Source-checked',
      },
      {
        name: 'Purple 30-Minute Timer',
        visualCues: 'A long-duration timer challenge; players describe waiting for the timer to finish.',
        position: 'GamesRef “Cabin Fever Long” marker: map x24.312%, y7.620%; elevation 74m.',
        prerequisiteItem: 'No carried item identified in the cross-checked sources.',
        transport: 'Position route is mapped; exact fastest transport is not established.',
        playerCount: 'Party-size behaviour pending first-hand verification.',
        verificationStatus: 'Community-reported',
      },
      {
        name: 'Purple Silent Number Room',
        visualCues: 'Separate rooms, changing numbers, and no direct verbal description of the hidden value.',
        position: 'GamesRef “Centurion Seance” marker: map x20.567%, y5.702%; elevation 38m. Exact handle-to-video match remains unverified.',
        prerequisiteItem: 'No carried item identified.',
        transport: 'No special transport identified.',
        playerCount: 'Multiple roles are shown; exact minimum pending first-hand verification.',
        verificationStatus: 'Community-reported',
      },
      {
        name: 'Purple Light Wall',
        visualCues: 'Wall lights or flashes used as counted signals between separated players.',
        position: 'Position TBD',
        prerequisiteItem: 'No carried item identified.',
        transport: 'No special transport identified.',
        playerCount: 'Separated co-op roles; exact scaling pending first-hand verification.',
        verificationStatus: 'Community-reported',
      },
      {
        name: 'Purple Music Box',
        visualCues: 'Music-box or sound cues, spaced objects, and taps on glass used for callouts.',
        position: 'Position TBD',
        prerequisiteItem: 'No carried item identified.',
        transport: 'No special transport identified.',
        playerCount: 'At least two distinct roles are shown; exact minimum pending first-hand verification.',
        verificationStatus: 'Community-reported',
      },
      {
        name: 'Purple Matching Rows',
        visualCues: 'Rows of objects or figures that players align to match a target arrangement.',
        position: 'Position TBD',
        prerequisiteItem: 'No carried item identified.',
        transport: 'No special transport identified.',
        playerCount: 'Co-op communication is shown; player-count differences are unverified.',
        verificationStatus: 'Community-reported',
      },
      {
        name: 'Purple Heavy Object Course',
        visualCues: 'Heavy object, obstacle course, raised gate, and backpack removal before the push.',
        position: 'Position TBD; the likely “Speed Obby” map-handle match is not published as fact.',
        prerequisiteItem: 'A heavy object must be moved through the course (community video).',
        transport: 'No vehicle identified; the object is moved through the obstacle route.',
        playerCount: 'Co-op shown; exact minimum and role scaling pending first-hand verification.',
        verificationStatus: 'Community-reported',
      },
    ],
    sources: [
      { title: 'All Purple Gourd Puzzle Solutions and Locations in Big Walk', publisher: 'YouTube player guide', url: 'https://www.youtube.com/watch?v=Sc3nY-sREbA' },
      { title: 'How to solve the Purple Flag Pole Golf Puzzle in Big Walk', publisher: 'YouTube player guide', url: 'https://www.youtube.com/watch?v=jqXvtfDx5zY' },
      { title: 'Big Walk community map', publisher: 'GamesRef / r/BigWalk map project', url: 'https://gamesref.com/game/big-walk/map' },
    ],
    relatedSlugs: ['puzzles/purple-things-where-to-use', 'walkthrough/green-room'],
    illustration: 'map',
    verificationLabel: 'Source-checked directory — mechanics still evidence-gated',
    updated: '2026-08-10',
    status: 'published', evidenceLevel: 'corroborated', indexable: true,
  },
  {
    slug: 'walkthrough', title: 'Big Walk Walkthroughs — Verification in Progress', h1: 'Big Walk Walkthroughs',
    description: 'A route-based walkthrough hub for Big Walk. Only first-hand, version-checked routes will be added.', active: 'walkthrough',
    scope: 'Use this hub to reach verified area walkthroughs. It intentionally does not invent routes, unlock conditions, or rewards before those details are observed.',
    evidenceNeeds: ['A complete first-hand route recording.', 'Landmark screenshots that can be independently matched.', 'A current-version check of all prerequisites and outcomes.'],
    relatedSlugs: ['walkthrough/red-tower-map-room', 'puzzles'], illustration: 'map', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer', title: 'Big Walk Multiplayer & Saves — Verification in Progress', h1: 'Big Walk Multiplayer and Saves',
    description: 'A single hub for first-hand Big Walk multiplayer, hosting, save, and connection notes.', active: 'multiplayer',
    scope: 'This hub separates questions about group play, hosting and saves, finding players, and reconnecting after a disconnect so evidence can be updated without blending different behaviours together.',
    evidenceNeeds: ['A controlled multiplayer session with the tested game version.', 'Host and joiner observations recorded separately.', 'Platform and save-state evidence for each conclusion.'],
    relatedSlugs: ['multiplayer/best-group-size', 'multiplayer/hosting-and-saves', 'multiplayer/transfer-save-to-new-host', 'multiplayer/how-to-find-players'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer/hosting-and-saves', title: 'Big Walk Hosting and Saves — Verification in Progress', h1: 'Big Walk Hosting and Saves',
    description: 'A first-hand reference for hosting, joining, leaving, and save behaviour in Big Walk is being prepared.', active: 'multiplayer',
    scope: 'The finished page will distinguish host behaviour from joiner behaviour and document only save handling that can be reproduced in the current version.',
    evidenceNeeds: ['A host session and a separate joiner session.', 'Observed save state before and after leaving.', 'Original screenshots or recordings of the relevant menus and prompts.'],
    relatedSlugs: ['multiplayer', 'multiplayer/transfer-save-to-new-host', 'troubleshooting/cant-rejoin-after-disconnect'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer/transfer-save-to-new-host', title: 'Transfer a Big Walk Save to a New Host — Verification in Progress', h1: 'Transfer a Big Walk Save to a New Host',
    description: 'This page is reserved for a verified save-transfer workflow, if the current game version supports one.', active: 'multiplayer',
    scope: 'No transfer path is claimed here yet. Once tested, the guide will state the exact supported conditions, platform limits, and recovery advice.',
    evidenceNeeds: ['A repeatable transfer test from the original host to a new host.', 'The exact platform and game version.', 'A before-and-after record that confirms what progress is preserved.'],
    relatedSlugs: ['multiplayer', 'multiplayer/hosting-and-saves'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'multiplayer/how-to-find-players', title: 'Find Big Walk Players — Verification in Progress', h1: 'How to Find Big Walk Players',
    description: 'A curated, safety-conscious list of active ways to find Big Walk players will be added after sources are checked.', active: 'multiplayer',
    scope: 'The finished page will link to official or clearly identified community spaces and explain what has been checked, instead of implying that a particular group is active.',
    evidenceNeeds: ['An official community or developer-listed contact point.', 'A date-checked community source where activity can be observed.', 'A review of safety and moderation expectations before linking.'],
    relatedSlugs: ['multiplayer', 'multiplayer/best-group-size'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting', title: 'Big Walk Troubleshooting — Verification in Progress', h1: 'Big Walk Troubleshooting',
    description: 'A diagnostic hub for reproducible Big Walk connection, voice, cross-play, and startup problems.', active: 'help',
    scope: 'Each troubleshooting topic will remain separate so reports for one platform or symptom are not mistakenly applied to every player.',
    evidenceNeeds: ['A reproducible issue report with platform and game version.', 'A confirmed resolution or a clearly labelled workaround.', 'A source or first-hand record for every technical recommendation.'],
    relatedSlugs: ['troubleshooting/cant-rejoin-after-disconnect', 'troubleshooting/voice-chat-not-working', 'troubleshooting/crossplay-switch-2', 'troubleshooting/white-screen-and-crash'], illustration: 'map', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting/cant-rejoin-after-disconnect', title: 'Cannot Rejoin Big Walk After a Disconnect — Verification in Progress', h1: 'Cannot Rejoin After a Disconnect',
    description: 'A reproducible diagnosis for Big Walk rejoin failures is being prepared.', active: 'help',
    scope: 'The completed guide will separate a temporary connection interruption from an unsupported session state and will name the tested platform and version.',
    evidenceNeeds: ['Steps that reproduce the rejoin failure.', 'Host and joiner observations.', 'A tested result for each proposed recovery step.'],
    relatedSlugs: ['troubleshooting', 'multiplayer/hosting-and-saves'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting/voice-chat-not-working', title: 'Big Walk Voice Chat Not Working — Verification in Progress', h1: 'Big Walk Voice Chat Not Working',
    description: 'A platform-specific Big Walk voice chat diagnostic is being prepared from reproducible tests.', active: 'help',
    scope: 'The completed guide will list only settings, permissions, and recovery steps that were tested on the named platform and game version.',
    evidenceNeeds: ['A tested voice session with each affected platform.', 'Recorded input and output device settings.', 'A repeatable result for every proposed fix.'],
    relatedSlugs: ['troubleshooting', 'multiplayer'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting/crossplay-switch-2', title: 'Big Walk Crossplay on Switch 2 — Verification in Progress', h1: 'Big Walk Crossplay on Switch 2',
    description: 'This page is reserved for a current, platform-specific crossplay check.', active: 'help',
    scope: 'No crossplay support is assumed. The page will publish availability, limits, and setup steps only after they are confirmed against the current version and platform guidance.',
    evidenceNeeds: ['Official platform support information or a first-hand cross-platform test.', 'The exact game build and platform versions.', 'A repeatable connection result.'],
    relatedSlugs: ['troubleshooting', 'multiplayer'], illustration: 'radio', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'troubleshooting/white-screen-and-crash', title: 'Big Walk White Screen or Crash — Verification in Progress', h1: 'Big Walk White Screen or Crash',
    description: 'A version-specific troubleshooting guide for white screens and crashes is being prepared.', active: 'help',
    scope: 'The eventual checklist will state the exact symptom, platform, and evidence behind each recovery step instead of presenting generic advice as a confirmed Big Walk fix.',
    evidenceNeeds: ['A reproducible start-up or in-session symptom.', 'System and game version details.', 'A tested resolution with a clear result.'],
    relatedSlugs: ['troubleshooting'], illustration: 'map', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
  {
    slug: 'beginner-guide/can-you-play-solo', title: 'Can You Play Big Walk Solo? — Verification in Progress', h1: 'Can You Play Big Walk Solo?',
    description: 'A first-hand answer about solo play in Big Walk is being prepared for the current version.', active: 'beginner',
    scope: 'This page will distinguish launching alone from completing content alone, and will avoid asserting availability or difficulty before a solo session is checked.',
    evidenceNeeds: ['A first-hand solo session in the current version.', 'Clear notes on where solo play is available or blocked.', 'Evidence for any content that materially changes with player count.'],
    relatedSlugs: ['beginner-guide', 'multiplayer/best-group-size'], illustration: 'walker', status: 'draft', evidenceLevel: 'not_collected', indexable: false,
  },
];

export function siteSectionBySlug(slug) {
  return siteSections.find((section) => section.slug === slug);
}

export function guideBySlug(slug) {
  return guides.find((guide) => guide.slug === slug);
}
