export const mapCategories = Object.freeze([
  { id: 'all', label: 'All locations' },
  { id: 'progression', label: 'Progression' },
  { id: 'puzzle', label: 'Puzzles' },
  { id: 'transport', label: 'Transport' },
  { id: 'item', label: 'Items & tools' },
  { id: 'ending', label: 'Ending' },
]);
export const mapPoints = Object.freeze([
  { id: 'opening-area', name: 'Opening area', category: 'progression', summary: 'Starting hub, equipment structures, and the return point for the complete-ending route.', landmark: 'Coast, lodge, and tutorial structures', href: '/beginner-guide', x: 13, y: 76, spoiler: false, sourceLabel: 'Official FAQ and current beginner guide' },
  { id: 'crosswalk', name: 'Crosswalk drawbridge', category: 'progression', summary: 'Complete the fixed opening challenges, return four rewards, shape the gold key, and lower the first bridge.', landmark: 'Raised red drawbridge above the beach', href: '/walkthrough/crosswalk', x: 23, y: 68, spoiler: false, sourceLabel: 'Source-checked Crosswalk route' },
  { id: 'map-room', name: 'Map Room', category: 'item', summary: 'Unlock the large progress map plus the portable map and compass through the Red Tower route.', landmark: 'Large stairs near the opening side of the island', href: '/walkthrough/red-tower-map-room', x: 29, y: 61, spoiler: false, sourceLabel: 'Source-checked Red Tower route' },
  { id: 'red-tower', name: 'Red Tower', category: 'progression', summary: 'Return five standard puzzle rewards, shape the released key, and open the Map Room.', landmark: 'Red tower above the Map Room route', href: '/walkthrough/red-tower-map-room', x: 37, y: 54, spoiler: false, sourceLabel: 'Source-checked Red Tower route' },
  { id: '4166-1899', name: '4166, 1899 button', category: 'puzzle', summary: 'Treat the numbers as coordinates, locate the hidden button, and split the hold-and-collect job between two players.', landmark: 'Rock line southeast of the opening hub', href: '/puzzles/4166-1899-coordinates', x: 47, y: 73, spoiler: false, sourceLabel: 'PC Gamer, source video, and current guide' },
  { id: 'sound-check', name: 'Sound Check', category: 'puzzle', summary: 'Chair, headphones, and six microphones inside the beige-and-red archway.', landmark: 'Yellow Tower side of the island', href: '/puzzles/green-chair-headphones', x: 49, y: 48, spoiler: false, sourceLabel: 'Source-checked Sound Check guide' },
  { id: 'colored-pegboard', name: 'Colored Pegboard', category: 'puzzle', summary: 'Collect 36 loose pieces around the circular board: nine red, nine yellow, nine green, and nine blue.', landmark: 'Circular board, bridge, outer wall, and raised beams', href: '/puzzles/colored-pegboard', x: 59, y: 61, spoiler: false, sourceLabel: 'Current guide and r/BigWalk missing-piece thread' },
  { id: 'blue-tower', name: 'Blue Tower', category: 'progression', summary: 'Return five rewards and shape the Blue Key for the train station.', landmark: 'Blue tower and red train tracks', href: '/walkthrough/blue-tower-train', x: 70, y: 47, spoiler: false, sourceLabel: 'Source-checked Blue Tower route' },
  { id: 'train-network', name: 'Train network', category: 'transport', summary: 'Insert the shaped Blue Key at the station, wait for the train, and ride it for Big Ride.', landmark: 'Station building beside red tracks', href: '/walkthrough/blue-tower-train', x: 67, y: 57, spoiler: false, sourceLabel: 'Source-checked Blue Tower route' },
  { id: 'green-tower', name: 'Green Tower', category: 'progression', summary: 'Return five rewards and shape the Green Key for the chairlift station.', landmark: 'Green tower above the lift network', href: '/walkthrough/green-tower-chairlift', x: 78, y: 65, spoiler: false, sourceLabel: 'Source-checked Green Tower route' },
  { id: 'chairlift', name: 'Chairlift network', category: 'transport', summary: 'Use the Green Tower key at the blue station with the red floor, then ride toward the highlands.', landmark: 'Blue station and moving chairs', href: '/walkthrough/green-tower-chairlift', x: 76, y: 54, spoiler: false, sourceLabel: 'Source-checked Green Tower route' },
  { id: 'forget-me-not', name: 'Forget-Me-Not console', category: 'puzzle', summary: 'Photograph the blue peninsula console slots, then recover matching sound, gesture, symbol, and dot pegs from earlier challenges.', landmark: 'Recessed blue console on a peninsula', href: '/puzzles/peg-puzzle', x: 87, y: 43, spoiler: false, sourceLabel: 'Wiki and current r/BigWalk reports' },
  { id: 'yellow-tower', name: 'Yellow Tower', category: 'progression', summary: 'Return five rewards and shape the Yellow Key for the tunnel entrance.', landmark: 'Yellow tower on the highland route', href: '/walkthrough/yellow-tower-tunnels', x: 60, y: 29, spoiler: false, sourceLabel: 'Source-checked Yellow Tower route' },
  { id: 'tunnel-network', name: 'Tunnel network', category: 'transport', summary: 'Open the yellow rockface entrance and use the underground network as a late-route shortcut.', landmark: 'Yellow tunnel door in the rockface', href: '/walkthrough/yellow-tower-tunnels', x: 53, y: 38, spoiler: false, sourceLabel: 'Source-checked Yellow Tower route' },
  { id: 'radio-network', name: 'Seven radio channels', category: 'item', summary: 'Use the colour, landmark, and coordinate checklist to unlock every music receiver.', landmark: 'Seven colour-coded music areas', href: '/walkthrough/radio-channels', x: 43, y: 43, spoiler: false, sourceLabel: 'Source-checked radio guide and soundtrack' },
  { id: 'black-tower', name: 'Black Tower', category: 'progression', summary: 'Trigger the one-player vision, complete the six-reward route, and collect the Black Key.', landmark: 'Tall dark monolith between the high routes', href: '/walkthrough/black-tower', x: 44, y: 23, spoiler: true, sourceLabel: 'Official FAQ, current guides, and r/BigWalk vision reports' },
  { id: 'wall-gate', name: 'The Wall', category: 'ending', summary: 'Use the Black Key here before continuing toward the Black Sphere and first ending.', landmark: 'Large gate beyond the Black Tower route', href: '/walkthrough/black-tower', x: 25, y: 16, spoiler: true, sourceLabel: 'Current Black Tower route sources' },
  { id: 'black-sphere', name: 'Black Sphere', category: 'ending', summary: 'Main-ending destination after the Wall and the route to Big Goodbye.', landmark: 'Giant dark sphere beyond the Wall', href: '/walkthrough/true-ending', x: 10, y: 10, spoiler: true, sourceLabel: 'Official ending confirmation and completion guides' },
  { id: 'purple-ridge', name: 'Purple challenge ridge', category: 'ending', summary: 'Seven harder post-game challenges that produce seven purple rewards for the 100% route.', landmark: 'Far ridge beyond the purple tunnel and chairlift side', href: '/puzzles/purple-challenges', x: 91, y: 23, spoiler: true, sourceLabel: 'Current video guides, community map, and r/BigWalk' },
  { id: 'completion-structure', name: '15-slot completion structure', category: 'ending', summary: 'Insert eight unused red rewards and seven purple rewards to produce the White Key.', landmark: 'Green structure near the opening and Map Room area', href: '/walkthrough/true-ending', x: 27, y: 71, spoiler: true, sourceLabel: 'Current completion guides and r/BigWalk guide thread' },
  { id: 'split-sphere', name: 'White Key destination', category: 'ending', summary: 'Use the White Key at the split black sphere near the opening area for the Big Game route.', landmark: 'Split sphere near the tutorial side of the island', href: '/walkthrough/true-ending', x: 16, y: 82, spoiler: true, sourceLabel: 'Current completion guides and trophy route' },
]);

export const mapSources = Object.freeze([
  { title: 'Big Walk FAQ', publisher: 'House House and Panic', url: 'https://bigwalk.game/faq/', note: 'Official world-size, host-save, accessibility, platform, and ending context.' },
  { title: 'Big Walk Map Room discussion', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vkdzd2/anyone_have_a_list_of_every_puzzle_yet/', note: 'Player reports for blue completion flags and tilted collected-but-not-deposited markers.' },
  { title: 'Big Walk interactive map discussion', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vmx4ue/new_big_walk_interactive_map_for_your_journey/', note: 'Community demand, spoiler concerns, and last-resort/completionist use.' },
  { title: 'MapGenie Big Walk map', publisher: 'MapGenie', url: 'https://mapgenie.io/big-walk/maps/island', note: 'External pixel-map reference for players who want exact third-party pins.' },
]);
