export const troubleshootingGuides = [
  {
    slug: 'cant-rejoin-after-disconnect',
    title: 'Big Walk Cannot Rejoin After Disconnect — Recovery Checks',
    h1: 'Cannot Rejoin Big Walk After a Disconnect',
    description: 'Use the current 1.4.10 network fixes, a fresh host session, and the exact error message to separate a stale session from a repeatable connection failure.',
    summary: 'Update both players to the current compatible build, then have the original host fully restart Big Walk, load the intended save, and create a fresh password-protected session. If joining still fails, copy the exact warning or error text before trying player-reported experiments.',
    updated: '2026-08-25',
    indexable: false,
    verificationLabel: 'Official 1.4.10 network changes + current community symptoms',
    quickChecks: [
      'Update the host and joiner before testing; Big Walk 1.4.10 added network stability, clearer errors, and host/join warnings.',
      'Confirm that the original host has opened the intended saved world and set the now-required Session Password.',
      'Use the newly displayed Join Code instead of a code from the disconnected session.',
      'Copy the exact error text and note whether failure occurs before loading, during loading, or after entering the world.',
    ],
    diagnosticSteps: [
      { title: 'Start with the official fixes', evidence: 'Official', action: 'Install the current build on both devices and read any warning shown on the host or join screen.', reason: 'Version 1.4.10 fixed a server hang after disconnects and added more specific network failures and connection warnings.' },
      { title: 'Recreate the host session', evidence: 'Official', action: 'The original save owner should close the game, reopen the intended world, set a Session Password, and share the new Join Code.', reason: 'The FAQ confirms host-owned saves, while 1.4.9 requires a password and a new session removes the previous session identifier from the test.' },
      { title: 'Classify and preserve the failure', evidence: 'Observed symptom', action: 'Record the exact error text plus rejection, endless loading, black screen, or crash.', reason: 'Steam and Reddit reports show multiple failure modes; a fix for one should not be presented as a fix for all.' },
      { title: 'Verify the system clock', evidence: 'Official', action: 'Confirm automatic date, time, and time-zone settings, restart the game, and run one controlled retry.', reason: 'The official FAQ says a significantly inaccurate clock can prevent hosting or joining. Mixed Steam results show that clock sync does not explain every connection failure.' },
    ],
    sources: [
      { title: 'Big Walk Version History', publisher: 'House House and Panic', url: 'https://bigwalk.game/history/', note: 'Official source for the 1.4.10 disconnect, network-error, host-warning, and voice-stability changes.' },
      { title: 'Big Walk FAQ', publisher: 'House House and Panic', url: 'https://bigwalk.game/faq/', note: 'Official source for host-owned saves, version compatibility, and Join Code behavior.' },
      { title: 'Connection to host timed out', publisher: 'Steam Community', url: 'https://steamcommunity.com/app/1478500/discussions/0/582804576516775705/', note: 'A 36-reply symptom thread with mixed results for clock sync and other experiments; no universal fix is established.' },
      { title: 'Looking for Group Megathread — 23 August 2026', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vvy13a/looking_for_group_megathread_23_august_2026/', note: 'Fresh reports of host errors, missing sessions, disconnects, and crash-driven room restarts after 1.4.10.' },
    ],
    evidenceNeeds: [
      'A repeatable host-and-joiner test on each affected platform and current game build.',
      'Confirmation of whether a fresh code changes the result for each distinct symptom.',
      'An official support note or patch note that identifies a cause or supported recovery path.',
    ],
    relatedSlugs: ['voice-chat-not-working', 'white-screen-and-crash', 'save-corrupted-or-missing'],
  },
  {
    slug: 'voice-chat-not-working',
    title: 'Big Walk Voice Chat Not Working — Proximity and Mic Checks',
    h1: 'Big Walk Voice Chat Not Working',
    description: 'Check proximity behavior, microphone input, permissions, and the current quiet-microphone patch before treating normal distance falloff as a fault.',
    summary: 'Test while standing beside another player. Big Walk deliberately uses proximity voice, so distant players becoming quiet or inaudible is expected behavior. A reported August 2026 patch raises very quiet microphone input, but it does not remove distance-based falloff.',
    updated: '2026-08-11',
    indexable: false,
    verificationLabel: 'Design behavior reported from developer patch notes; device steps need local testing',
    quickChecks: [
      'Stand directly beside another player before testing input and output.',
      'Confirm the intended microphone is the operating system default input device.',
      'Check that Big Walk has microphone permission and that the microphone is not muted.',
      'Install the current game update, then restart the game after changing device settings.',
    ],
    diagnosticSteps: [
      { title: 'Rule out normal proximity falloff', evidence: 'Official', action: 'Have two players stand side by side and speak at normal volume.', reason: 'The game intentionally limits how far voices carry; long-distance silence is not evidence that voice chat is broken.' },
      { title: 'Check the captured input', evidence: 'Platform check', action: 'Verify the active system input device, its level meter, mute state, and Big Walk microphone permission.', reason: 'This separates a device or permission problem from the game’s spatial voice behavior.' },
      { title: 'Compare both directions', evidence: 'Diagnostic', action: 'Test A hearing B, then B hearing A, without changing distance.', reason: 'One-way failure usually points to one player’s input or the other player’s output path.' },
      { title: 'Retest on the current patch', evidence: 'Official', action: 'Update and fully restart both clients before repeating the close-range test.', reason: 'Version 1.4.10 improves voice stability, while the earlier quiet-microphone patch raised low input without removing proximity falloff.' },
    ],
    sources: [
      { title: 'Big Walk FAQ', publisher: 'House House', url: 'https://bigwalk.game/faq/', note: 'Official game and multiplayer context.' },
      { title: 'Big Walk patch addresses voice volume complaints', publisher: 'PC Gamer', url: 'https://www.pcgamer.com/games/puzzle/big-walk-patch-addresses-voice-volume-complaints-with-restraint-we-consider-it-an-important-part-of-the-games-design-that-you-can-only-hear-players-who-are-close-to-you/', note: 'Reports the developer patch note: quiet microphones were boosted while proximity remained part of the design.' },
    ],
    evidenceNeeds: [
      'Current close-range voice tests on PC and PS5, including one-way failure cases.',
      'Screenshots of relevant operating-system and in-game audio controls.',
      'Official troubleshooting guidance for permissions, selected devices, or known platform-specific faults.',
    ],
    relatedSlugs: ['cant-rejoin-after-disconnect', 'white-screen-and-crash'],
  },
  {
    slug: 'white-screen-and-crash',
    title: 'Big Walk White Screen or Crash — Startup Triage',
    h1: 'Big Walk White Screen or Crash',
    description: 'Separate a white screen at launch, join-time black screen, progressive frame-rate collapse, and hard lock before testing safe current-version checks.',
    summary: 'Update first, then classify the failure. A white screen before the menu, a black screen while joining, and frame rate degrading into a hard lock are different reports. On PC, verify files, set the official Frame Rate Limit, keep Vsync enabled, and change one variable per retry.',
    updated: '2026-08-25',
    indexable: false,
    verificationLabel: 'Safe platform checks + clearly labelled community reports',
    quickChecks: [
      'Write down whether the failure occurs at launch, while joining, or after entering a world.',
      'Install pending game, launcher, operating-system, and graphics-driver updates.',
      'On version 1.4.9 or later, set a Frame Rate Limit and leave Vsync enabled for one controlled in-session test.',
      'On Steam, verify the installed game files before reinstalling the entire game.',
    ],
    diagnosticSteps: [
      { title: 'Name the exact symptom', evidence: 'Observed symptom', action: 'Record screen color, error text, whether audio continues, whether frame rate decays first, and the last visible screen.', reason: 'White-screen launch, black-screen join, and progressive hard-lock reports may have different causes.' },
      { title: 'Apply the official display controls', evidence: 'Official', action: 'Update to the current version, enable Vsync, choose a conservative Frame Rate Limit, and retry the same scene once.', reason: 'Version 1.4.9 added frame limiting, enabled Vsync by default, and added half-rate Vsync; this is safer than assuming a hardware-specific cause.' },
      { title: 'Restore a known-good install state', evidence: 'Platform check', action: 'Restart the device, update graphics drivers, then use Steam file verification before reinstalling.', reason: 'These reversible platform checks do not assume a Big Walk-specific root cause.' },
      { title: 'Test launch peripherals carefully', evidence: 'Player report', action: 'Only for a white screen before the menu, disconnect one nonessential USB device, retry once, then reconnect it.', reason: 'Several Steam users reported a USB-C keyboard workaround, while another said it did not help. It is not a confirmed fix for join-time or in-session crashes.' },
      { title: 'Stop after a hard lock', evidence: 'Safety boundary', action: 'If the display, input, or whole PC locks again, stop repeating the test and send platform, build, hardware, logs, and the shortest reproduction to support.', reason: 'Repeated hard resets can risk data loss, and current forum evidence does not establish a safe universal Big Walk fix.' },
    ],
    sources: [
      { title: 'Verify integrity of game files', publisher: 'Steam Support', url: 'https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB', note: 'Platform-level file verification guidance.' },
      { title: 'Big Walk Version History', publisher: 'House House and Panic', url: 'https://bigwalk.game/history/', note: 'Official source for Frame Rate Limit, Vsync, savedata protection, and current-version changes.' },
      { title: 'White screen upon launch', publisher: 'Steam Community', url: 'https://steamcommunity.com/app/1478500/discussions/0/591811861507218649/', note: 'Multiple reports that removing a USB-C keyboard helped launch; one report says it did not. This remains a symptom-specific experiment.' },
      { title: 'Black screen upon joining or hosting lobby', publisher: 'Reddit community report', url: 'https://www.reddit.com/r/BigWalk/comments/1vglb2n/black_screen_upon_joining_hosting_lobby/', note: 'A separate join-time symptom report.' },
      { title: 'Game crash my whole computer', publisher: 'Steam Community', url: 'https://steamcommunity.com/app/1478500/discussions/0/591811861507453535/', note: 'Cross-hardware reports of progressive frame-rate loss, black screen with audio, hard lock, and shutdown through 14 August.' },
    ],
    evidenceNeeds: [
      'A reproducible launch failure with current build, platform, and hardware details.',
      'Controlled before-and-after results for file verification and peripheral tests.',
      'Official known-issue or patch-note confirmation before promoting any Big Walk-specific fix.',
    ],
    relatedSlugs: ['cant-rejoin-after-disconnect', 'voice-chat-not-working', 'save-corrupted-or-missing'],
  },
  {
    slug: 'save-corrupted-or-missing',
    title: 'Big Walk Save Corrupted or Missing — Safe Recovery Checks',
    h1: 'Big Walk Save Corrupted or Missing',
    description: 'Preserve the original Big Walk save, check the current build and available backups, and separate a missing host world from true file corruption.',
    summary: 'Do not overwrite the only copy. First confirm that the original host opened the correct world. On PC, close Big Walk and make a backup copy of the entire save_games folder before inspecting Windows Previous Versions or any community recovery option. Previous Versions may not be available and recovery is not guaranteed.',
    updated: '2026-08-25',
    indexable: false,
    verificationLabel: 'Official save protection + community recovery reports',
    quickChecks: [
      'Confirm that the original host—not a former joiner—is checking the missing world.',
      'Install the current game update; version 1.4.9 added better protection against potential savedata loss.',
      'Close Big Walk before copying the full save_games folder to a separate backup location.',
      'Preserve the current files even if a Windows Previous Versions snapshot is not available.',
    ],
    diagnosticSteps: [
      { title: 'Rule out the wrong host', evidence: 'Official', action: 'Ask the player who originally hosted to open their saved-world list.', reason: 'The official FAQ says world progress belongs to the host. A joiner not seeing that world is expected and is not evidence of corruption.' },
      { title: 'Freeze the current state', evidence: 'Safety boundary', action: 'Exit the game and copy the full PC save_games folder to a separate backup before replacing or editing any file.', reason: 'A preserved copy keeps current evidence recoverable if a later experiment fails.' },
      { title: 'Check Windows Previous Versions', evidence: 'Player report', action: 'Open the save_games folder properties and inspect Previous Versions. If a dated snapshot exists, open it and copy the candidate .sav file elsewhere before any comparison.', reason: 'One Reddit player reported recovery after a power loss, while another said no usable prior version existed. This method is not available or successful on every system.' },
      { title: 'Escalate without destructive edits', evidence: 'Support path', action: 'Record the game version, platform, failure event, folder backup, and whether the save appears blank or absent, then contact House House support through the official FAQ.', reason: 'Official history confirms improved protection but does not publish a universal repair tool or guarantee that a damaged save can be restored.' },
    ],
    sources: [
      { title: 'Big Walk Version History', publisher: 'House House and Panic', url: 'https://bigwalk.game/history/', note: 'Official confirmation that version 1.4.9 added better protection against potential savedata loss.' },
      { title: 'Big Walk FAQ', publisher: 'House House and Panic', url: 'https://bigwalk.game/faq/', note: 'Official host-save behavior and support path.' },
      { title: 'Help with save file', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vl9pnm/help_with_save_file/', note: 'A power-loss corruption report plus a community Windows Previous Versions recovery method with a reported failure in the same thread.' },
      { title: 'Lost save', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vli17t/lost_save/', note: 'A separate report of a blank save after a crash near Black Tower; no universal recovery was established.' },
    ],
    evidenceNeeds: [
      'Official documentation of save locations and supported recovery steps for each platform.',
      'A controlled before-and-after recovery using a copied save on the current version.',
      'Confirmation of whether cloud-save behavior differs across Steam, PS5, and Switch 2.',
    ],
    relatedSlugs: ['cant-rejoin-after-disconnect', 'white-screen-and-crash'],
  },
];

export function troubleshootingBySlug(slug) {
  return troubleshootingGuides.find((guide) => guide.slug === slug);
}
