export const troubleshootingGuides = [
  {
    slug: 'cant-connect-or-join',
    title: "Big Walk Can't Connect or Join — Host, Code & EOS Checks",
    h1: "Big Walk Can't Connect or Join a Game",
    description: 'Separate a missing friend game, invalid code or password, connection timeout, EOS failure, and join-time crash before changing network settings.',
    summary: 'Start with the host: update both devices, load the intended save fully, read any host warning, and share the current password and Join Code. If every room fails, check version compatibility, the system clock, and Epic Online Services in that order. Preserve the exact error text because one symptom does not have one universal fix.',
    gameVersion: '1.5.0',
    sourceCheckedAt: '2026-08-28',
    updated: '2026-08-28',
    indexable: false,
    verificationLabel: 'Official connection checks + current symptom threads',
    symptomRows: [
      { symptom: "Friend's game is not listed", likelyBoundary: 'Friend-list visibility or the Mac App Store limitation', nextStep: 'Add the host on the current platform or use the active Join Code instead.' },
      { symptom: 'Session unavailable or password rejected', likelyBoundary: 'Stale code, changed password, or ended session', nextStep: 'Ask the host to read both values from the current Session Details screen.' },
      { symptom: 'Connection to host timed out', likelyBoundary: 'Host session, version, EOS, clock, or network path', nextStep: 'Run the official checks below and keep the exact timeout text.' },
      { symptom: 'Cannot host or join any room', likelyBoundary: 'Epic Online Services reachability or significantly inaccurate clock', nextStep: 'Check automatic date/time, EOS access, and the official host/join warning.' },
      { symptom: 'Black screen, white screen, or crash while joining', likelyBoundary: 'Startup or join-time failure rather than simple session discovery', nextStep: 'Use the dedicated startup/crash page and preserve the last visible screen.' },
    ],
    quickChecks: [
      'Install the current build on the host and joiner; version 1.4.10 added network stability, clearer errors, and host/join warnings.',
      'Confirm that the original host opened the intended save and fully loaded their character into the world.',
      'Read the required Session Password and current Join Code from Session Details instead of reusing an older post or screenshot.',
      'Copy the exact error text and note whether failure occurs before loading, during loading, or after entering the world.',
      'Change one variable per retry so a successful join can be traced to a specific check.',
    ],
    diagnosticSteps: [
      { title: 'Classify and preserve the failure', evidence: 'Observed symptom', action: 'Record the exact error text plus missing listing, rejection, timeout, endless loading, black screen, or crash.', reason: 'Steam and Reddit reports show multiple failure modes; a fix for one should not be presented as a fix for all.' },
      { title: 'Load the host world completely', evidence: 'Official', action: 'The original save owner should open the intended world and wait until their character is loaded before anyone joins.', reason: 'The official FAQ lists a running, loaded host world as the first connection requirement.' },
      { title: 'Choose friends list or Join Code', evidence: 'Official', action: 'Add the host on the same platform service, or bypass discovery with the current Join Code. Mac App Store players must use a code.', reason: "The FAQ documents both paths and says the Mac App Store build does not show a friend's games list." },
      { title: 'Refresh the code and password', evidence: 'Official', action: 'Read the required password and current Join Code from Session Details. Restart the host session if either value came from an older session.', reason: 'A new code is generated when the host starts, and version 1.4.9 made Session Passwords required.' },
      { title: 'Compare the first two version numbers', evidence: 'Official', action: 'Check every player on the title or menu screen. Update if the first or second number differs.', reason: 'The FAQ says only the first two version numbers must match; a third-number difference is compatible.' },
      { title: 'Fully restart the game and device', evidence: 'Official', action: 'Close Big Walk on host and joiner, reopen it, retry once, then reboot rather than only sleeping the device if the failure remains.', reason: 'The official connection checklist recommends a full game restart and then a computer or console reboot.' },
      { title: 'Verify the system clock', evidence: 'Official', action: 'Confirm automatic date, time, and time-zone settings, restart the game, and run one controlled retry.', reason: 'The official FAQ says a significantly inaccurate clock can prevent hosting or joining. Mixed Steam results show that clock sync does not explain every connection failure.' },
      { title: 'Check Epic Online Services and proxy state', evidence: 'Official', action: 'Follow the FAQ EOS reachability check. On a personal PC only, review proxy state before using the FAQ reset command; on managed networks, contact the administrator instead.', reason: 'The FAQ links all-room host/join failure to EOS reachability and lists proxy or router blocking as possible boundaries, not confirmed causes for every timeout.' },
    ],
    sources: [
      { title: 'Big Walk Version History', publisher: 'House House and Panic', url: 'https://bigwalk.game/history/', note: 'Official source for the 1.4.10 disconnect, network-error, host-warning, and voice-stability changes.' },
      { title: 'Big Walk FAQ', publisher: 'House House and Panic', url: 'https://bigwalk.game/faq/', note: 'Official source for host-owned saves, version compatibility, and Join Code behavior.' },
      { title: 'Connection to host timed out', publisher: 'Steam Community', url: 'https://steamcommunity.com/app/1478500/discussions/0/582804576516775705/', note: 'A 36-reply symptom thread with mixed results for clock sync and other experiments; no universal fix is established.' },
      { title: 'Looking for Group Megathread — 27 August 2026', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vzklgx/looking_for_group_megathread_27_august_2026/', note: 'Fresh missing-session, reconnect, crash-restart, and password-change reports; room codes are ephemeral.' },
    ],
    evidenceNeeds: [
      'A repeatable host-and-joiner test on each affected platform and current game build.',
      'Confirmation of whether a fresh code changes the result for each distinct symptom.',
      'An official support note or patch note that identifies a cause or supported recovery path.',
    ],
    relatedSlugs: ['voice-chat-not-working', 'white-screen-and-crash', 'save-corrupted-or-missing'],
  },
  {
    slug: 'voice-chat-not-working',
    title: 'Big Walk Voice Chat Not Working — Proximity and Mic Checks',
    h1: 'Big Walk Voice Chat Not Working',
    description: 'Separate expected proximity falloff from microphone input, moderation, Bluetooth, PS5, macOS, and network voice failures on the current build.',
    summary: 'Test while standing beside another player. Normal proximity falloff is expected, but no Microphone Activity, one-way audio, a Bluetooth input/output mismatch, or voices cutting out at close range needs a different check. Version 1.4.8 normalized quiet microphone output, while 1.4.10 improved voice stability.',
    gameVersion: '1.5.0',
    sourceCheckedAt: '2026-08-28',
    updated: '2026-08-28',
    indexable: false,
    verificationLabel: 'Official platform checks + current symptom reports',
    symptomHeading: 'Where does voice fail?',
    symptomRows: [
      { symptom: 'A distant player fades or becomes inaudible', likelyBoundary: 'Expected proximity behavior', nextStep: 'Stand side by side before treating distance falloff as a fault.' },
      { symptom: 'Microphone Activity does not move', likelyBoundary: 'Input device, hardware mute, permission, or Hold-to-talk state', nextStep: 'Check the in-game meter and the platform input path.' },
      { symptom: 'The meter moves, but nobody hears you', likelyBoundary: 'Mute Mode, moderation silence, output path, or one-way session fault', nextStep: 'Compare both directions and inspect Session moderation.' },
      { symptom: 'Players are very quiet while standing together', likelyBoundary: 'Input level or pre-1.4.8 quiet-microphone behavior', nextStep: 'Update, speak for several seconds, and verify system input level.' },
      { symptom: 'Bluetooth has audio but no mic, or mic but poor/mono audio', likelyBoundary: 'Headphone device versus Headset device', nextStep: 'Assign both Big Walk input and output to the headset-capable device.' },
      { symptom: 'Voices cut out after working normally', likelyBoundary: 'Voice-session or network stability', nextStep: 'Update through the 1.4.10 stability fixes, then run one controlled rejoin.' },
    ],
    quickChecks: [
      'Stand directly beside another player before testing input and output.',
      'Open Settings > Audio and confirm that Microphone Activity moves when you speak.',
      'Check hardware mute, Mute Mode, and whether anyone is silenced in Moderation Settings.',
      'Confirm the intended input and output devices and Big Walk microphone permission.',
      'Install the current update, then fully restart the game after changing one device setting.',
    ],
    platformChecks: [
      { platform: 'All platforms', symptom: 'Mic meter is flat or another player is silenced', check: 'Check hardware mute, Microphone Activity, Mute Mode, and the moderation menu.', evidence: 'Official FAQ' },
      { platform: 'Windows 11 + Bluetooth', symptom: 'Audio works but mic does not, or output becomes low-quality mono', check: 'Open Volume Mixer while Big Walk runs and assign both input and output to the Headset device, not the headphone-only device.', evidence: 'Official FAQ' },
      { platform: 'PlayStation 5', symptom: 'Controller or headset mic works elsewhere but not in Big Walk', check: 'Press the PS button, open Sound, and turn Mute Game Voice Chat Off.', evidence: 'Official FAQ' },
      { platform: 'macOS', symptom: 'No microphone input', check: 'Open Privacy & Security > Microphone and enable Big Walk. Restart the game after granting permission.', evidence: 'Official FAQ' },
      { platform: 'Apple Silicon Mac', symptom: 'Game audio or voices cut out under load', check: 'Close heavy background apps, lower graphics quality, and test a wired headset because CPU, GPU, and sound share resources.', evidence: 'Official FAQ' },
    ],
    diagnosticSteps: [
      { title: 'Rule out normal proximity falloff', evidence: 'Official', action: 'Have two players stand side by side and speak at normal volume.', reason: 'The game intentionally limits how far voices carry; long-distance silence is not evidence that voice chat is broken.' },
      { title: 'Read the in-game microphone meter', evidence: 'Official', action: 'Open Settings > Audio and speak while watching Microphone Activity.', reason: 'A flat meter points toward input selection, permission, hardware mute, or Hold-to-talk before spatial output is involved.' },
      { title: 'Check mute and moderation state', evidence: 'Official', action: 'Check hardware mute, Mute Mode, the required talk button, and whether the affected player is silenced under Moderation Settings.', reason: 'These official controls can block speech even when the operating system sees the microphone.' },
      { title: 'Compare both directions', evidence: 'Diagnostic', action: 'Test A hearing B, then B hearing A, without changing distance.', reason: 'One-way failure usually points to one player’s input or the other player’s output path.' },
      { title: 'Match input and output devices', evidence: 'Official', action: 'Confirm Big Walk uses the intended microphone and listening device. For Bluetooth, select the Headset device for both directions.', reason: 'A headphone-only Bluetooth profile can provide stereo output without microphone input, while the headset profile supports both at lower audio quality.' },
      { title: 'Apply the platform-specific check', evidence: 'Official', action: 'Use the PS5 voice-chat toggle, macOS microphone permission, or Windows 11 Volume Mixer row that matches the affected platform.', reason: 'The official FAQ publishes distinct checks, so a Windows Bluetooth step should not be generalized to every device.' },
      { title: 'Retest on the current patch', evidence: 'Official', action: 'Update and fully restart both clients before repeating the close-range test.', reason: 'Version 1.4.8 normalized quiet microphone output and 1.4.10 improved voice stability without removing proximity falloff.' },
      { title: 'Separate voice dropout from network trouble', evidence: 'Official', action: 'If voices and player movement drop together, use the connection page and check the host network and frame rate.', reason: 'The FAQ links intermittent voices and erratic player movement to network conditions, especially when the host is affected.' },
      { title: 'Run one controlled rejoin', evidence: 'Player report', action: 'If only one player stops hearing specific teammates after all official checks, let that player leave and rejoin once.', reason: 'A Steam thread reports that rejoining can restore voice, but this is a symptom-specific community result rather than a universal fix.' },
    ],
    sources: [
      { title: 'Big Walk FAQ', publisher: 'House House and Panic', url: 'https://bigwalk.game/faq/', note: 'Official proximity, text chat, Microphone Activity, mute, Bluetooth, PS5, macOS, echo, and network guidance.' },
      { title: 'Big Walk Version History', publisher: 'House House and Panic', url: 'https://bigwalk.game/history/', note: 'Official 1.4.8 quiet-microphone normalization and 1.4.10 voice-stability changes.' },
      { title: 'Big Walk patch addresses voice volume complaints', publisher: 'PC Gamer', url: 'https://www.pcgamer.com/games/puzzle/big-walk-patch-addresses-voice-volume-complaints-with-restraint-we-consider-it-an-important-part-of-the-games-design-that-you-can-only-hear-players-who-are-close-to-you/', note: 'Reports the developer patch note: quiet microphones were boosted while proximity remained part of the design.' },
      { title: "Bug report: Can't hear other players", publisher: 'Steam Community', url: 'https://steamcommunity.com/app/1478500/discussions/0/591812126801542491/', note: 'One current voice-dropout report and a player-reported rejoin result.' },
      { title: 'Proximity Chat Cross Platform', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vn5un0/proximity_chat_cross_platform/', note: 'Independent reports across PS5, Steam Deck, Switch 2, Mac, and mixed-platform rooms; not a substitute for device troubleshooting.' },
    ],
    evidenceNeeds: [
      'Current close-range voice tests on PC and PS5, including one-way failure cases.',
      'Screenshots of relevant operating-system and in-game audio controls.',
      'Before-and-after results for the official PS5, macOS, and Windows Bluetooth checks.',
    ],
    relatedSlugs: ['cant-connect-or-join', 'white-screen-and-crash'],
  },
  {
    slug: 'white-screen-and-crash',
    title: 'Big Walk White Screen or Crash — Startup Triage',
    h1: 'Big Walk White Screen or Crash',
    description: 'Separate a white screen at launch, join-time black screen, progressive frame-rate collapse, and hard lock before testing safe current-version checks.',
    summary: 'Update first, then classify the failure. A white screen before the menu, a black screen while joining, and frame rate degrading into a hard lock are different reports. On PC, verify files, set the official Frame Rate Limit, keep Vsync enabled, and change one variable per retry.',
    updated: '2026-08-25',
    indexable: false,
    verificationLabel: 'Safe platform checks + clearly labelled community reports',
    quickChecks: [
      'Write down whether the failure occurs at launch, while joining, or after entering a world.',
      'Install pending game, launcher, operating-system, and graphics-driver updates.',
      'On version 1.4.9 or later, set a Frame Rate Limit and leave Vsync enabled for one controlled in-session test.',
      'On Steam, verify the installed game files before reinstalling the entire game.',
    ],
    diagnosticSteps: [
      { title: 'Name the exact symptom', evidence: 'Observed symptom', action: 'Record screen color, error text, whether audio continues, whether frame rate decays first, and the last visible screen.', reason: 'White-screen launch, black-screen join, and progressive hard-lock reports may have different causes.' },
      { title: 'Apply the official display controls', evidence: 'Official', action: 'Update to the current version, enable Vsync, choose a conservative Frame Rate Limit, and retry the same scene once.', reason: 'Version 1.4.9 added frame limiting, enabled Vsync by default, and added half-rate Vsync; this is safer than assuming a hardware-specific cause.' },
      { title: 'Restore a known-good install state', evidence: 'Platform check', action: 'Restart the device, update graphics drivers, then use Steam file verification before reinstalling.', reason: 'These reversible platform checks do not assume a Big Walk-specific root cause.' },
      { title: 'Test launch peripherals carefully', evidence: 'Player report', action: 'Only for a white screen before the menu, disconnect one nonessential USB device, retry once, then reconnect it.', reason: 'Several Steam users reported a USB-C keyboard workaround, while another said it did not help. It is not a confirmed fix for join-time or in-session crashes.' },
      { title: 'Stop after a hard lock', evidence: 'Safety boundary', action: 'If the display, input, or whole PC locks again, stop repeating the test and send platform, build, hardware, logs, and the shortest reproduction to support.', reason: 'Repeated hard resets can risk data loss, and current forum evidence does not establish a safe universal Big Walk fix.' },
    ],
    sources: [
      { title: 'Verify integrity of game files', publisher: 'Steam Support', url: 'https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB', note: 'Platform-level file verification guidance.' },
      { title: 'Big Walk Version History', publisher: 'House House and Panic', url: 'https://bigwalk.game/history/', note: 'Official source for Frame Rate Limit, Vsync, savedata protection, and current-version changes.' },
      { title: 'White screen upon launch', publisher: 'Steam Community', url: 'https://steamcommunity.com/app/1478500/discussions/0/591811861507218649/', note: 'Multiple reports that removing a USB-C keyboard helped launch; one report says it did not. This remains a symptom-specific experiment.' },
      { title: 'Black screen upon joining or hosting lobby', publisher: 'Reddit community report', url: 'https://www.reddit.com/r/BigWalk/comments/1vglb2n/black_screen_upon_joining_hosting_lobby/', note: 'A separate join-time symptom report.' },
      { title: 'Game crash my whole computer', publisher: 'Steam Community', url: 'https://steamcommunity.com/app/1478500/discussions/0/591811861507453535/', note: 'Cross-hardware reports of progressive frame-rate loss, black screen with audio, hard lock, and shutdown through 14 August.' },
    ],
    evidenceNeeds: [
      'A reproducible launch failure with current build, platform, and hardware details.',
      'Controlled before-and-after results for file verification and peripheral tests.',
      'Official known-issue or patch-note confirmation before promoting any Big Walk-specific fix.',
    ],
    relatedSlugs: ['cant-connect-or-join', 'voice-chat-not-working', 'save-corrupted-or-missing'],
  },
  {
    slug: 'save-corrupted-or-missing',
    title: 'Big Walk Save Corrupted or Missing — Safe Recovery Checks',
    h1: 'Big Walk Save Corrupted or Missing',
    description: 'Preserve the original Big Walk save, check the current build and available backups, and separate a missing host world from true file corruption.',
    summary: 'Do not overwrite the only copy. First confirm that the original host opened the correct world. On PC, close Big Walk and make a backup copy of the entire save_games folder before inspecting Windows Previous Versions or any community recovery option. Previous Versions may not be available and recovery is not guaranteed.',
    updated: '2026-08-25',
    indexable: false,
    verificationLabel: 'Official save protection + community recovery reports',
    quickChecks: [
      'Confirm that the original host—not a former joiner—is checking the missing world.',
      'Install the current game update; version 1.4.9 added better protection against potential savedata loss.',
      'Close Big Walk before copying the full save_games folder to a separate backup location.',
      'Preserve the current files even if a Windows Previous Versions snapshot is not available.',
    ],
    diagnosticSteps: [
      { title: 'Rule out the wrong host', evidence: 'Official', action: 'Ask the player who originally hosted to open their saved-world list.', reason: 'The official FAQ says world progress belongs to the host. A joiner not seeing that world is expected and is not evidence of corruption.' },
      { title: 'Freeze the current state', evidence: 'Safety boundary', action: 'Exit the game and copy the full PC save_games folder to a separate backup before replacing or editing any file.', reason: 'A preserved copy keeps current evidence recoverable if a later experiment fails.' },
      { title: 'Check Windows Previous Versions', evidence: 'Player report', action: 'Open the save_games folder properties and inspect Previous Versions. If a dated snapshot exists, open it and copy the candidate .sav file elsewhere before any comparison.', reason: 'One Reddit player reported recovery after a power loss, while another said no usable prior version existed. This method is not available or successful on every system.' },
      { title: 'Escalate without destructive edits', evidence: 'Support path', action: 'Record the game version, platform, failure event, folder backup, and whether the save appears blank or absent, then contact House House support through the official FAQ.', reason: 'Official history confirms improved protection but does not publish a universal repair tool or guarantee that a damaged save can be restored.' },
    ],
    sources: [
      { title: 'Big Walk Version History', publisher: 'House House and Panic', url: 'https://bigwalk.game/history/', note: 'Official confirmation that version 1.4.9 added better protection against potential savedata loss.' },
      { title: 'Big Walk FAQ', publisher: 'House House and Panic', url: 'https://bigwalk.game/faq/', note: 'Official host-save behavior and support path.' },
      { title: 'Help with save file', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vl9pnm/help_with_save_file/', note: 'A power-loss corruption report plus a community Windows Previous Versions recovery method with a reported failure in the same thread.' },
      { title: 'Lost save', publisher: 'r/BigWalk', url: 'https://www.reddit.com/r/BigWalk/comments/1vli17t/lost_save/', note: 'A separate report of a blank save after a crash near Black Tower; no universal recovery was established.' },
    ],
    evidenceNeeds: [
      'Official documentation of save locations and supported recovery steps for each platform.',
      'A controlled before-and-after recovery using a copied save on the current version.',
      'Confirmation of whether cloud-save behavior differs across Steam, PS5, and Switch 2.',
    ],
    relatedSlugs: ['cant-connect-or-join', 'white-screen-and-crash'],
  },
];

export function troubleshootingBySlug(slug) {
  return troubleshootingGuides.find((guide) => guide.slug === slug);
}
